/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

//! Every vDSO function a kernel exports must be a classified [`VdsoSymbol`].

use std::collections::BTreeSet;

use object::Object;
use object::ObjectSymbol;
use object::SymbolKind;
use object::SymbolSection;
use reverie::vdso::VdsoHandling;
use reverie::vdso::VdsoSymbol;

/// The global symbols of the latest Linux release's vDSO for this
/// architecture, generated by `vdso/linux-vdso-symbols.sh`.
#[cfg(target_arch = "x86_64")]
const LATEST_LINUX: &str = include_str!("vdso/linux-v7.2-x86_64.txt");
#[cfg(target_arch = "aarch64")]
const LATEST_LINUX: &str = include_str!("vdso/linux-v7.2-aarch64.txt");

fn listed_names(list: &str) -> Vec<&str> {
    list.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .collect()
}

/// The functions exported by this process's vDSO, selected as reverie-ptrace's
/// `vdso_exports` selects them: only data and bookkeeping symbols are skipped.
fn running_kernel_exports() -> Vec<String> {
    let maps = procfs::process::Process::myself().unwrap().maps().unwrap();
    let vdso = maps
        .iter()
        .find(|map| map.pathname == procfs::process::MMapPath::Vdso)
        .expect("this host must map a vDSO");
    // SAFETY: the kernel keeps the vDSO mapped, readable and unmodified for the
    // life of the process, and nothing in this test binary patches it.
    let image = unsafe {
        std::slice::from_raw_parts(
            vdso.address.0 as *const u8,
            (vdso.address.1 - vdso.address.0) as usize,
        )
    };
    let elf = object::File::parse(image).expect("the vDSO must parse as ELF");
    elf.dynamic_symbols()
        .filter(|symbol| {
            symbol.is_global()
                && !symbol.is_undefined()
                && symbol.section() != SymbolSection::Absolute
                && !matches!(
                    symbol.kind(),
                    SymbolKind::Data | SymbolKind::Tls | SymbolKind::Section | SymbolKind::File
                )
        })
        .map(|symbol| symbol.name().unwrap().to_owned())
        .collect()
}

#[test]
fn each_variant_displays_as_its_symbol_name() {
    let mut names = BTreeSet::new();
    for symbol in VdsoSymbol::ALL {
        assert_eq!(symbol.to_string(), symbol.name());
        assert_eq!(VdsoSymbol::from_name(symbol.name()), Some(*symbol));
        assert!(names.insert(symbol.name()), "{symbol} is listed twice");
    }
    assert_eq!(VdsoSymbol::from_name("__vdso_not_a_function"), None);
}

/// The enum is exactly the latest release's symbol list: a name the kernel
/// adds fails here until it has a variant, which does not compile until
/// `VdsoSymbol::class` classifies it.
#[test]
fn latest_linux_vdso_symbols_are_exactly_the_variants() {
    let listed = listed_names(LATEST_LINUX);
    let unclassified: Vec<&str> = listed
        .iter()
        .copied()
        .filter(|name| VdsoSymbol::from_name(name).is_none())
        .collect();
    assert!(
        unclassified.is_empty(),
        "vDSO symbols with no VdsoSymbol variant: {unclassified:?}"
    );
    let listed: BTreeSet<&str> = listed.into_iter().collect();
    let unlisted: Vec<&str> = VdsoSymbol::ALL
        .iter()
        .map(|symbol| symbol.name())
        .filter(|name| !listed.contains(name))
        .collect();
    assert!(
        unlisted.is_empty(),
        "VdsoSymbol variants missing from the checked-in symbol list: {unlisted:?}"
    );
}

#[test]
fn running_kernel_vdso_exports_are_all_classified() {
    let exports = running_kernel_exports();
    assert!(!exports.is_empty());
    let unclassified: Vec<&String> = exports
        .iter()
        .filter(|name| VdsoSymbol::from_name(name).is_none())
        .collect();
    assert!(
        unclassified.is_empty(),
        "the running kernel's vDSO exports functions with no VdsoSymbol variant: \
         {unclassified:?}; add each to reverie/src/vdso.rs and classify it"
    );
    for name in &exports {
        println!("{name}: {:?}", VdsoSymbol::from_name(name).unwrap().class());
    }
}

/// An alias shares its entry point, so it must share its class.
#[test]
fn aliases_have_the_class_of_their_vdso_name() {
    for symbol in VdsoSymbol::ALL {
        if let Some(prefixed) = VdsoSymbol::from_name(&format!("__vdso_{}", symbol.name())) {
            assert_eq!(symbol.class(), prefixed.class(), "{symbol} and {prefixed}");
        }
    }
}

/// Only a function whose result depends on nothing outside the guest may keep
/// the kernel's code.
#[test]
fn only_deterministic_functions_stay_native() {
    for symbol in VdsoSymbol::ALL {
        let class = symbol.class();
        if class.handling == VdsoHandling::Native {
            assert!(class.input.is_deterministic(), "{symbol}: {class:?}");
        }
    }
}

/// The in-guest backends written in C each keep a copy of the classification
/// as a header; reverie-dbt and reverie-sabre compare theirs with this.
#[cfg(target_arch = "x86_64")]
#[test]
fn c_header_lists_every_variant() {
    let header = reverie::vdso::c_header();
    for symbol in VdsoSymbol::ALL {
        assert!(
            header.contains(&format!("{{\"{symbol}\", ")),
            "{symbol} is missing from the C header"
        );
    }
}
