"""Typed subset of GDB's embedded Python API used by vendored helper scripts."""

COMMAND_DATA: int
COMMAND_OBSCURE: int
COMMAND_USER: int
COMPLETE_FILENAME: int
PARAM_OPTIONAL_FILENAME: int
PARAM_STRING: int
PARAM_ZINTEGER: int
VERSION: str


class Command:
    def __init__(
        self, name: str, command_class: int, completer_class: int = ...
    ) -> None: ...
    def dont_repeat(self) -> None: ...


class Parameter:
    value: str | int | None
    set_doc: str
    show_doc: str
    def __init__(self, name: str, command_class: int, parameter_class: int) -> None: ...


class Breakpoint:
    def __init__(self, spec: str, *, internal: bool = ...) -> None: ...
    def delete(self) -> None: ...


class Inferior:
    pid: int


class Value:
    def __int__(self) -> int: ...
    def string(self) -> str: ...


class Frame:
    def read_var(self, name: str) -> Value: ...


def execute(
    command: str, from_tty: bool = ..., to_string: bool = ...
) -> str: ...
def parameter(name: str) -> bool: ...
def parse_and_eval(expression: str) -> int: ...
def selected_inferior() -> Inferior: ...
def string_to_argv(arguments: str) -> list[str]: ...
def newest_frame() -> Frame: ...
def breakpoints() -> tuple[Breakpoint, ...] | None: ...
