[patch."https://github.com/rrnewton/reverie.git"]
reverie-core = { path = "/home/newton/work/dev-hermit/worktrees/slots/kvm-fchmodat2/reverie" }
reverie-dbt = { path = "/home/newton/work/dev-hermit/worktrees/slots/kvm-fchmodat2/reverie-dbt" }
reverie-kvm = { path = "/home/newton/work/dev-hermit/worktrees/slots/kvm-fchmodat2/reverie-kvm" }
reverie-liteinst = { path = "/home/newton/work/dev-hermit/worktrees/slots/kvm-fchmodat2/reverie-liteinst" }
reverie-memory = { path = "/home/newton/work/dev-hermit/worktrees/slots/kvm-fchmodat2/reverie-memory" }
reverie-ptrace = { path = "/home/newton/work/dev-hermit/worktrees/slots/kvm-fchmodat2/reverie-ptrace" }
reverie-rpc-transport = { path = "/home/newton/work/dev-hermit/worktrees/slots/kvm-fchmodat2/reverie-rpc-transport" }
reverie-sabre = { path = "/home/newton/work/dev-hermit/worktrees/slots/kvm-fchmodat2/experimental/reverie-sabre" }
reverie-syscalls = { path = "/home/newton/work/dev-hermit/worktrees/slots/kvm-fchmodat2/reverie-syscalls" }
