/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * @generated by `reverie::vdso::c_header()` from `VdsoSymbol::class` in
 * reverie/src/vdso.rs, which documents each entry. Do not edit: the test that
 * compares this file with the generator rewrites it when run with
 * REVERIE_BLESS=1.
 */

#ifndef REVERIE_VDSO_SYMBOLS_H
#define REVERIE_VDSO_SYMBOLS_H

#include <string.h>

/* What a backend that patches the x86_64 vDSO does with an entry point. */
enum reverie_vdso_handling {
  /* Replace it with a stub that issues `syscall`. */
  REVERIE_VDSO_SYSCALL,
  /* Replace it with a stub that returns -ENOSYS. */
  REVERIE_VDSO_ENOSYS,
  /* Leave the kernel's code in place. */
  REVERIE_VDSO_NATIVE,
};

struct reverie_vdso_symbol {
  const char* name;
  enum reverie_vdso_handling handling;
  /* The syscall for REVERIE_VDSO_SYSCALL, otherwise -1. */
  long syscall;
};

/* Every function the x86_64 vDSO exports, by its kernel name. */
static const struct reverie_vdso_symbol reverie_vdso_symbols[] = {
    {"clock_gettime", REVERIE_VDSO_SYSCALL, 228},
    {"__vdso_clock_gettime", REVERIE_VDSO_SYSCALL, 228},
    {"gettimeofday", REVERIE_VDSO_SYSCALL, 96},
    {"__vdso_gettimeofday", REVERIE_VDSO_SYSCALL, 96},
    {"getcpu", REVERIE_VDSO_SYSCALL, 309},
    {"__vdso_getcpu", REVERIE_VDSO_SYSCALL, 309},
    {"time", REVERIE_VDSO_SYSCALL, 201},
    {"__vdso_time", REVERIE_VDSO_SYSCALL, 201},
    {"clock_getres", REVERIE_VDSO_SYSCALL, 229},
    {"__vdso_clock_getres", REVERIE_VDSO_SYSCALL, 229},
    {"__vdso_sgx_enter_enclave", REVERIE_VDSO_ENOSYS, -1},
    {"getrandom", REVERIE_VDSO_SYSCALL, 318},
    {"__vdso_getrandom", REVERIE_VDSO_SYSCALL, 318},
    {"__vdso_futex_robust_list64_try_unlock", REVERIE_VDSO_NATIVE, -1},
    {"__vdso_futex_robust_list32_try_unlock", REVERIE_VDSO_NATIVE, -1},
};

/*
 * The entry for the vDSO function named `name`, or NULL if it is unknown, in
 * which case it is replaced with -ENOSYS like REVERIE_VDSO_ENOSYS.
 */
static inline const struct reverie_vdso_symbol* reverie_vdso_symbol_lookup(
    const char* name) {
  for (size_t index = 0;
       index < sizeof(reverie_vdso_symbols) / sizeof(reverie_vdso_symbols[0]);
       index++) {
    if (strcmp(reverie_vdso_symbols[index].name, name) == 0)
      return &reverie_vdso_symbols[index];
  }
  return NULL;
}

#endif /* REVERIE_VDSO_SYMBOLS_H */
