/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

//! Everything defined here shouldn't be used directly. However, they must be
//! exposed so that code generated by the proc macros can use them.

#![doc(hidden)]
use core::ptr;
use core::sync::atomic::AtomicPtr;
use core::sync::atomic::Ordering::AcqRel;
use core::sync::atomic::Ordering::Acquire;

use reverie_rpc::MakeClient;

use super::callbacks;
use super::ffi;
use super::paths;
use super::rpc;
use super::signal;
use super::tool::Tool;
use super::tool::ToolGlobal;

/// Creates an instance of a Tool. This is called when `ToolGlobal::global` is
/// called for the first time.
pub fn init_tool<T: Tool>() -> T {
    // Create the base transport channel. This transport layer can be wrapped
    // potentially many times by nested tools. If this fails (i.e., it failed to
    // connect to the socket), there isn't anything we can do except panic. A
    // client without a connection to the global state isn't very useful.
    let channel = rpc::BaseChannel::new().unwrap();

    T::new(MakeClient::make_client(Box::new(channel)))
}

fn register_detours<T: ToolGlobal>(fn_icept_reg: ffi::icept_reg_fn) {
    for detour_func in <<T as ToolGlobal>::Target>::detours() {
        fn_icept_reg(detour_func);
    }
}

// This is the fixed initialization ABI exported to the SaBRe loader.
#[allow(clippy::not_unsafe_ptr_arg_deref, clippy::too_many_arguments)]
pub fn sbr_init<T: ToolGlobal>(
    argc: *mut i32,
    argv: *mut *mut *mut libc::c_char,
    fn_icept_reg: ffi::icept_reg_fn,
    vdso_callback: *mut Option<ffi::handle_vdso_fn>,
    syscall_handler: *mut Option<ffi::handle_syscall_fn>,
    rdtsc_handler: *mut Option<ffi::handle_rdtsc_fn>,
    _post_load: *mut Option<ffi::post_load_fn>,
    sabre_path: *const libc::c_char,
    client_path: *const libc::c_char,
) {
    unsafe {
        *vdso_callback = Some(callbacks::handle_vdso::<T>);
        *syscall_handler = Some(callbacks::handle_syscall::<T>);
        *rdtsc_handler = Some(callbacks::handle_rdtsc::<T>);

        paths::set_sabre_path(sabre_path);
        paths::set_client_path(client_path);

        // The plugin path is the first argument.
        paths::set_plugin_path(**argv);

        signal::register_central_handler::<T>();

        *argc -= 1;
        *argv = (*argv).wrapping_add(1);

        // Setting up function detours
        register_detours::<T>(fn_icept_reg);
    }
}

struct ProcessValue<T> {
    pid: libc::pid_t,
    value: T,
}

/// A process-local lazy value that detects when `fork` copied its storage.
///
/// Published values are intentionally never reclaimed. `get_or_init` returns
/// a static reference, so retaining prior generations is required when a
/// forked child replaces its copied pointer. The parent has a separate address
/// space and continues using its original value.
pub struct ProcessCell<T> {
    current: AtomicPtr<ProcessValue<T>>,
}

impl<T> ProcessCell<T> {
    pub const fn new() -> Self {
        Self {
            current: AtomicPtr::new(ptr::null_mut()),
        }
    }

    pub fn get_or_init(&'static self, init: fn() -> T) -> &'static T {
        let pid = unsafe { syscalls::raw::syscall0(syscalls::Sysno::getpid) as libc::pid_t };

        loop {
            let current = self.current.load(Acquire);
            if !current.is_null() && unsafe { (*current).pid == pid } {
                return unsafe { &(*current).value };
            }

            let candidate = Box::into_raw(Box::new(ProcessValue { pid, value: init() }));
            match self
                .current
                .compare_exchange(current, candidate, AcqRel, Acquire)
            {
                Ok(_) => return unsafe { &(*candidate).value },
                Err(actual) => {
                    // This candidate was never published, so it is safe to
                    // destroy. A competing initialization may have won.
                    unsafe { drop(Box::from_raw(candidate)) };
                    if !actual.is_null() && unsafe { (*actual).pid == pid } {
                        return unsafe { &(*actual).value };
                    }
                }
            }
        }
    }
}

impl<T> Default for ProcessCell<T> {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod process_cell_tests {
    use std::sync::Mutex;
    use std::sync::mpsc;

    use super::ProcessCell;

    struct LockedState(Mutex<()>);

    fn new_locked_state() -> LockedState {
        LockedState(Mutex::new(()))
    }

    #[test]
    fn fork_reinitializes_instead_of_inheriting_a_locked_transport() {
        static CELL: ProcessCell<LockedState> = ProcessCell::new();
        let state = CELL.get_or_init(new_locked_state);
        let (locked_tx, locked_rx) = mpsc::channel();
        let (release_tx, release_rx) = mpsc::channel();

        let worker = std::thread::spawn(move || {
            let _guard = state.0.lock().unwrap();
            locked_tx.send(()).unwrap();
            release_rx.recv().unwrap();
        });
        locked_rx.recv().unwrap();

        let mut pipe = [0; 2];
        assert_eq!(0, unsafe { libc::pipe(pipe.as_mut_ptr()) });
        let child = unsafe { libc::fork() };
        assert!(child >= 0);
        if child == 0 {
            unsafe { libc::close(pipe[0]) };
            let child_state = CELL.get_or_init(new_locked_state);
            let acquired = child_state.0.try_lock().is_ok() as u8;
            unsafe {
                libc::write(pipe[1], &acquired as *const u8 as *const _, 1);
                libc::_exit(0);
            }
        }

        unsafe { libc::close(pipe[1]) };
        let mut poll_fd = libc::pollfd {
            fd: pipe[0],
            events: libc::POLLIN,
            revents: 0,
        };
        let ready = unsafe { libc::poll(&mut poll_fd, 1, 1_000) };
        if ready != 1 {
            unsafe { libc::kill(child, libc::SIGKILL) };
            release_tx.send(()).unwrap();
            worker.join().unwrap();
            unsafe { libc::waitpid(child, core::ptr::null_mut(), 0) };
            panic!("child blocked on inherited process mutex");
        }

        let mut acquired = 0u8;
        let read = unsafe { libc::read(pipe[0], &mut acquired as *mut u8 as *mut _, 1) };
        assert_eq!(read, 1, "child blocked on inherited process mutex");
        assert_eq!(acquired, 1);
        release_tx.send(()).unwrap();
        worker.join().unwrap();

        let mut status = 0;
        assert_eq!(child, unsafe { libc::waitpid(child, &mut status, 0) });
        assert!(libc::WIFEXITED(status));
        assert_eq!(libc::WEXITSTATUS(status), 0);
    }
}
