from pathlib import Path
import json,hashlib,copy,difflib
A=Path(__file__).resolve().parent.parent;d=A/'push-12d4ce8c-v1';prior=A/'push-9db60ab9-v2';p=json.loads((prior/'plan.json').read_bytes());sha=lambda x:hashlib.sha256(Path(x).read_bytes()).hexdigest()
def item(path):return {'path':str(path),'sha256':sha(path)}
def write(path,data):
 with Path(path).open('x') as f:json.dump(data,f,indent=2);f.write('\n')
report=Path('/home/newton/work/dev-hermit/worktrees/slots/kvm-parent-reader-support-20260916/ignored/reverie-cleanup-claude-review-12d4ce8c/REPORT.md');assert sha(report)=='3341a272cad1ae9277ab82b1ce8a77027c436d30b4b35f4005d71e0efb6e1ed8'
bodyold=A/'cleanup-after-fatal-v1/pr-body-12d4ce8c.md';body=bodyold.read_text();old='Independent native source review accepted the exact correction; actual Claude review of `12d4ce8c` is pending at this preparation cutoff. Approval labels and landing must describe the actual final verdicts, not that pending status.';new='Independent native source review and actual Claude review both approved exactly `12d4ce8c0bc426f1ae41416f5b4a699e2c300879`. Those source verdicts are separate from the final runtime evidence described above; no pending execution was credited by the source reviews.';assert old in body;body=body.replace(old,new)
needle='Existing first-cleanup-error retention is unchanged.';addition=' Existing first-cleanup-error retention is unchanged. The approved review also records a nonblocking limitation: when a concurrent natural join takes the child handle first, its cached derived marker can still produce a different intermediate cleanup error shape. Public completion removes that marker when a real run failure was published; the intermediate result without that failure context is not normalized by this correction.';assert needle in body;body=body.replace(needle,addition.strip())
bodypath=d/'pr-body-12d4ce8c-approved.md'
with bodypath.open('x') as f:f.write(body)
p['head']='12d4ce8c0bc426f1ae41416f5b4a699e2c300879';p['remote_branch']='refs/heads/codex/kvm-fatal-cleanup-20260917';p['preserved_remote_refs']={p.pop('preserved_remote_branch'):p.pop('preserved_remote_tip'),'refs/heads/codex/kvm-prejoin-failure-20260917':'9db60ab95587d4cb5e0438dfeca409471eb9baf5'}
p['source_plans']=[item(A/n/'plan.json') for n in ['futex-full-library-v3','qualification-execution-v8','qualification-build-v7','lint-v15']]
paths=[Path(i['path']) for i in p['inputs'] if not str(i['path']).startswith(str(A))]
paths += [A/n/filename for n in ['futex-full-library-v3','qualification-execution-v7','qualification-execution-v8','qualification-build-v7','lint-v15'] for filename in ['RESULT.json','REPORT.md','TERMINAL.json']]
paths += [report,bodypath,d/'remote-preparation.json',prior/'plan.json',prior/'launch.py',A/'cleanup-after-fatal-v1/PUBLICATION-PREPARATION.json',A/'source-v25-preparation/binding.json',A/'source-v25-preparation/REPORT.md']
p['inputs']=[item(x) for x in paths];p['validation_results']={'full':str(A/'futex-full-library-v3/RESULT.json'),'static':str(A/'qualification-execution-v8/RESULT.json'),'build':str(A/'qualification-build-v7/RESULT.json'),'lint':str(A/'lint-v15/RESULT.json')}
p['environment_fixed']['TMPDIR']=str(d/'run-1/tmp');p['run_root']=str(d/'run-1');p['execution']=['/usr/bin/python3','-B',str(d/'launch.py')]
s=p['stage'];s['out']=s['out'].replace('reverie-push-9db60ab9-v2','reverie-push-12d4ce8c-v1');s['payload'][-1]='HEAD:'+p['remote_branch'];s['argv'][s['argv'].index('--out')+1]=s['out'];s['argv']=s['argv'][:s['argv'].index('--log-bytes')+2]+s['payload']
p['authority']='Root authorized normal first push of exactly 12d4 to new absent codex/kvm-fatal-cleanup-20260917 after actual source approval and local source/helper/ELF checks. Preserve old 696f and 9db branches, registered local branch and every prior result. No force, hook bypass or PR creation.'
p['prior_interpreter_boundary']=p.pop('preserved_first_attempt');write(d/'plan.json',p)
text=(prior/'launch.py').read_text().replace(sha(prior/'plan.json'),sha(d/'plan.json'))
text=text.replace("        helper['check_executable'](plans[0]['artifact'])\n        for artifact in plans[1]['artifacts'].values():\n            helper['check_executable'](artifact)","        for source_plan in plans:\n            for artifact in source_plan.get('artifacts', {}).values():\n                helper['check_executable'](artifact)")
text=text.replace("plan['remote_branch'], plan['preserved_remote_branch']], plan['source_root'])", "plan['remote_branch'], *plan['preserved_remote_refs']], plan['source_root'])")
text=text.replace("        assert refs[plan['preserved_remote_branch']] == plan['preserved_remote_tip'], refs", "        assert all(refs.get(branch) == tip for branch, tip in plan['preserved_remote_refs'].items()), refs")
a=text.index("        native = json.loads(");b=text.index("        before = remote('remote-before')",a)
text=text[:a]+"        results = {name: json.loads(Path(path).read_text())\n                   for name, path in plan['validation_results'].items()}\n        assert results['full']['status'] == 'passed'\n        assert results['full']['registered_count'] == 454\n        assert results['full']['outcome_counts'] == {'ok': 454, 'failed': 0, 'ignored': 0}\n        qualification = results['static']\n        assert qualification['status'] == 'passed with one explicitly retained accounting retry'\n        assert qualification['original_methods'] == 22\n        assert qualification['accepted_first_attempts'] == 21 and qualification['accepted_retries'] == 1\n        assert len(qualification['rows']) == 22\n        assert results['build']['status'] == results['lint']['status'] == 'passed'\n"+text[b:]
with (d/'launch.py').open('x') as f:f.write(text)
with (d/'caller-increment.patch').open('x') as f:f.writelines(difflib.unified_diff((prior/'launch.py').read_text().splitlines(True),text.splitlines(True),fromfile='push-9db-v2/launch.py',tofile='push-12d-v1/launch.py'))
write(d/'PREPARATION.json',{'head':p['head'],'body':item(bodypath),'claude_approval':item(report),'plan':item(d/'plan.json'),'caller':item(d/'launch.py'),'source_plans':p['source_plans'],'preserved_remote_refs':p['preserved_remote_refs'],'authority':p['authority']})
print(json.dumps({'plan':sha(d/'plan.json'),'caller':sha(d/'launch.py'),'body':sha(bodypath),'packet':sha(d/'PREPARATION.json'),'inputs':len(p['inputs'])}))
