from pathlib import Path
import json,hashlib,runpy,subprocess
A=Path(__file__).resolve().parent.parent;d=A/'futex-full-library-v3';run=d/'run-1';h=runpy.run_path(str(d/'launch.py'),run_name='readback_only');p,f,old,names=h['load_checked']();sha=f['digest'];s=json.loads((run/'summary.json').read_bytes());assert s['status']=='passed';o=Path(p['stage']['out']);r=json.loads((o/'result.json').read_bytes());outcomes=json.loads((run/'native-outcomes.json').read_bytes());old['require_complete_population'](outcomes,names);admission,exit=h['check_admission'](p,r,f)
assert outcomes['outcome_counts']=={'ok':454,'failed':0,'ignored':0};assert not outcomes['kvm_unavailable_diagnostics']
terminal=[]
for _ in range(2):
 cmd=['/usr/bin/systemctl','--user','show',r['authenticated_service']['unit'],'--property=LoadState,ActiveState,SubState,MainPID,ControlGroup'];q=subprocess.run(cmd,capture_output=True,text=True,timeout=10);v=dict(x.split('=',1) for x in q.stdout.splitlines());assert q.returncode==0 and v['ActiveState']=='inactive' and v['MainPID']=='0' and v['ControlGroup']==''
 terminal.append(dict(argv=cmd,exit=q.returncode,stdout=q.stdout,stderr=q.stderr))
def write(path,v):
 with path.open('x') as t:json.dump(v,t,indent=2);t.write('\n')
write(d/'TERMINAL.json',terminal)
result=dict(status='passed',source_head=p['source_head'],source_binding_sha256=sha(p['source_binding']),plan_sha256=sha(d/'plan.json'),caller_sha256=sha(d/'launch.py'),launch_sha256=sha(run/'launch.json'),outcome_counts=outcomes['outcome_counts'],registered_count=len(names),cpu_seconds=s['aggregate_cpu_nsec']/1e9,wall_seconds=s['wall_seconds'],service=r['authenticated_service'],result_sha256=sha(o/'result.json'),stdout_sha256=sha(o/'stdout'),stderr_sha256=sha(o/'stderr'),stdout_bytes=(o/'stdout').stat().st_size,stderr_bytes=(o/'stderr').stat().st_size,outcomes_sha256=sha(run/'native-outcomes.json'),summary_sha256=sha(run/'summary.json'),source_after_sha256=sha(run/'source-after.json'),terminal_sha256=sha(d/'TERMINAL.json'),admission_sha256=sha(p['stage']['admission_record']),artifact=p['artifacts']['lib'],input_count=len(p['inputs']),scope=p['scope'])
write(d/'RESULT.json',result)
with (d/'REPORT.md').open('x') as t:t.write(f"The full serial library passed all 454 methods on the first execution of committed 12d4ce8c: 454 passed, 0 failed, 0 ignored, 0 filtered. All prior 453 names and original 427 are present; the only added method is the eight-case cleanup control. The three methods that failed in the prior 450/3 run now pass with their direct error and cleanup assertions intact.\n\nActual API 12 admission and REVERIE_REQUIRE_KVM=1 were required. The service used {result['cpu_seconds']:.6f} CPU seconds and {result['wall_seconds']:.9f} observed wall seconds, below the unchanged 30 CPU / 60 wall / 16 GiB / zero swap / 1 MiB limits. Payload and admission exit 0, complete accounting, and two fresh inactive/empty service readbacks are retained. Raw output is bounded and untruncated.\n\nThe full run includes all 44 previously selected native methods and all four earlier VM methods, so they are not repeated separately. The original 22 static integration methods remain next. Full source, all 199 inputs, actual ELF and admission checks pass after execution.\n\nThe original 426/1 futex enrollment timing failure remains unexplained, and the prior 450/3 result remains retained. No unchanged-run retry was used here. This is Reverie component evidence, not a Hermit strict INFO, repeat-determinism or canonical parity result.\n")
print(json.dumps({'RESULT':sha(d/'RESULT.json'),'REPORT':sha(d/'REPORT.md'),'TERMINAL':sha(d/'TERMINAL.json'),'summary':sha(run/'summary.json'),'cpu':result['cpu_seconds'],'wall':result['wall_seconds']}))
