from pathlib import Path
import hashlib,json,runpy,subprocess,re
A=Path(__file__).resolve().parent.parent;d=A/'qualification-execution-v8';p=json.loads((d/'plan.json').read_bytes());run=d/'run-1';summary=json.loads((run/'summary.json').read_bytes());assert summary['status']=='passed' and len(summary['completed'])==16 and len(summary['prior_accepted'])==6
f=runpy.run_path(p['helpers']['path'],run_name='readback_only');sha=f['digest'];f['check_inputs'](p)
for e in p['artifacts'].values():f['check_executable'](e)
prior=json.loads(Path(p['continuation']['original_plan']).read_bytes());stages=prior['stages'][:6]+p['stages'];accepted=summary['prior_accepted']+summary['completed'];assert [x['test'] for x in accepted]==p['selected_tests']['static-elf']
rows=[];terminal=[]
for i,(s,accepted_row) in enumerate(zip(stages,accepted)):
 o=Path(s['out']);r=json.loads((o/'result.json').read_bytes());assert r['wrapper_exit_code']==0 and r['observer_error'] is None and r['stop_reason'] is None and r['accounting_complete'] and r['comparison_eligible'] and r['final_accounting']['cgroup_empty']
 raw=(o/'stdout').read_text();err=(o/'stderr').read_text();assert 'skipping ' not in (raw+err).lower();assert re.findall(r'^test (.+) \.\.\. ok$',raw,re.M)==[s['test']];assert re.findall(r'^test result: ok\. (\d+) passed; (\d+) failed; (\d+) ignored; (\d+) measured; (\d+) filtered out;',raw,re.M)==[('1','0','0','0','287')]*s['expected_summaries']
 adp=Path(s['admission_record']);ad=json.loads(adp.read_bytes());ae=json.loads(adp.with_suffix('.exit.json').read_bytes());assert ae=={'exit':0};assert ad['api_version']==12 and ad['supervisor_pid']==r['authenticated_service']['main_process']['pid'];assert ad['test_binary']=={k:p['artifacts']['static-elf'][k] for k in ['path','sha256','bytes','mode']};assert r['authenticated_service']['initial_properties']['ControlGroup'] in ad['cgroup']
 assert sha(o/'stdout')==accepted_row['stdout_sha256'] and sha(o/'stderr')==accepted_row['stderr_sha256']
 fresh=[]
 for _ in range(2):
  cmd=['/usr/bin/systemctl','--user','show',r['authenticated_service']['unit'],'--property=LoadState,ActiveState,SubState,MainPID,ControlGroup'];q=subprocess.run(cmd,capture_output=True,text=True,timeout=10);v=dict(x.split('=',1) for x in q.stdout.splitlines());assert q.returncode==0 and v['ActiveState']=='inactive' and v['MainPID']=='0' and v['ControlGroup']=='';fresh.append(dict(argv=cmd,exit=q.returncode,stdout=q.stdout,stderr=q.stderr))
 terminal.append(dict(stage=s['name'],readbacks=fresh))
 rows.append(dict(stage=s['name'],test=s['test'],classification='accepted retry after observer refusal' if i==6 else 'accepted first attempt',cpu_seconds=r['final_accounting']['cpu_usage_nsec']/1e9,wall_seconds=r['elapsed_seconds'],service=r['authenticated_service'],result_path=str(o/'result.json'),result_sha256=sha(o/'result.json'),stdout_sha256=sha(o/'stdout'),stderr_sha256=sha(o/'stderr'),stdout_bytes=(o/'stdout').stat().st_size,stderr_bytes=(o/'stderr').stat().st_size,admission_sha256=sha(adp)))
def write(path,v):
 with path.open('x') as out:json.dump(v,out,indent=2);out.write('\n')
write(d/'TERMINAL.json',terminal);f['check_inputs'](p)
result=dict(status='passed with one explicitly retained accounting retry',head=p['source_head'],source_binding_sha256=sha(p['source_binding']),plan_sha256=sha(d/'plan.json'),caller_sha256=sha(d/'launch.py'),launch_sha256=sha(run/'launch.json'),original_methods=22,accepted_first_attempts=21,accepted_retries=1,refusal_preserved=str(Path(p['continuation']['original_plan']).parent/'RESULT.json'),rows=rows,accepted_cpu_seconds=sum(x['cpu_seconds'] for x in rows),accepted_summed_stage_wall_seconds=sum(x['wall_seconds'] for x in rows),continuation_cpu_seconds=sum(x['cpu_seconds'] for x in rows[6:]),continuation_summed_stage_wall_seconds=sum(x['wall_seconds'] for x in rows[6:]),terminal_sha256=sha(d/'TERMINAL.json'),full_source_and_inputs_verified=True,input_count=len(p['inputs']),scope=p['scope'])
write(d/'RESULT.json',result)
with (d/'REPORT.md').open('x') as out:out.write(f"All original 22 static integration methods are now accepted on committed 12d4ce8c: 21 first attempts and one explicitly recorded retry after observer accounting refusal. The original stage 07 refusal remains refused. The continuation ran exactly original 07–22; it did not repeat the six already accepted methods or any library methods. No product assertion failed, no source/helper changed and no resource bound increased.\n\nThe 16 continuation services used {result['continuation_cpu_seconds']:.6f} CPU seconds and {result['continuation_summed_stage_wall_seconds']:.9f} summed observed stage wall seconds. Accepted evidence across all 22 methods totals {result['accepted_cpu_seconds']:.6f} CPU seconds and {result['accepted_summed_stage_wall_seconds']:.9f} summed observed stage wall seconds; the refused attempt is separate. Every accepted stage has actual API 12 admission, REVERIE_REQUIRE_KVM=1, exact named output, expected recursive summary counts, complete accounting and two fresh inactive/empty readbacks.\n\nThe original ten-mode diagnostic method, all 17 leader methods and all four terminal-fork methods are retained. Original child writes, status 0, wait events, typed diagnostic and distinct cleanup assertions passed. Exact stdout/stderr, source/258 inputs, emitted ELF and admission records are bound. Raw output is bounded and untruncated.\n\nThe separate complete serial library run passed all 454 methods first attempt and already includes the selected native/four-VM population. The historical 426/1 futex timing failure remains unexplained; prior 450/3 and all observer refusals remain retained. This is Reverie component qualification, not Hermit INFO, determinism or canonical parity evidence.\n")
print(json.dumps({'RESULT':sha(d/'RESULT.json'),'REPORT':sha(d/'REPORT.md'),'TERMINAL':sha(d/'TERMINAL.json'),'cpu':result['accepted_cpu_seconds'],'wall':result['accepted_summed_stage_wall_seconds']}))
