from pathlib import Path
import json,hashlib,runpy,subprocess,re
A=Path(__file__).resolve().parent.parent;d=A/'qualification-execution-v7';p=json.loads((d/'plan.json').read_bytes());f=runpy.run_path(p['helpers']['path'],run_name='readback_only');sha=f['digest'];f['check_inputs'](p)
for e in p['artifacts'].values():f['check_executable'](e)
summary=json.loads((d/'run-1/summary.json').read_bytes());assert summary['active_stage']=='static-elf-07' and len(summary['completed'])==6
rows=[];term=[]
for i,s in enumerate(p['stages'][:7]):
 o=Path(s['out']);r=json.loads((o/'result.json').read_bytes());ad=json.loads(Path(s['admission_record']).read_bytes());ae=json.loads(Path(s['admission_record']).with_suffix('.exit.json').read_bytes());assert ae=={'exit':0};assert ad['api_version']==12 and ad['supervisor_pid']==r['authenticated_service']['main_process']['pid'] and ad['test_binary']=={k:p['artifacts']['static-elf'][k] for k in ['path','sha256','bytes','mode']}
 stdout=(o/'stdout').read_text();stderr=(o/'stderr').read_text();assert 'skipping ' not in (stdout+stderr).lower();assert re.findall(r'^test (.+) \.\.\. ok$',stdout,re.M)==[s['test']];assert re.findall(r'^test result: ok\. (\d+) passed; (\d+) failed; (\d+) ignored; (\d+) measured; (\d+) filtered out;',stdout,re.M)==[('1','0','0','0','287')]
 if i<6:assert r['accounting_complete'] and r['comparison_eligible'] and r['observer_error'] is None
 else:
  assert r['observer_error']=='OSError: [Errno 19] No such device' and not r['accounting_complete'] and r['final_accounting'] is None
  rec=r['refusal_final_accounting'];initial=r['authenticated_service']['initial_properties'];assert rec['properties']['ExecMainPID']==initial['ExecMainPID'] and rec['properties']['ExecMainStartTimestampMonotonic']==initial['ExecMainStartTimestampMonotonic'];assert rec['cpu_usage_nsec']==327610000 and rec['cgroup_empty'] and rec['exec_main_status']==0
 reads=[]
 for _ in range(2):
  cmd=['/usr/bin/systemctl','--user','show',r['authenticated_service']['unit'],'--property=LoadState,ActiveState,SubState,MainPID,ControlGroup'];q=subprocess.run(cmd,capture_output=True,text=True,timeout=10);v=dict(x.split('=',1) for x in q.stdout.splitlines());assert q.returncode==0 and v['ActiveState']=='inactive' and v['MainPID']=='0' and v['ControlGroup']=='';reads.append(dict(argv=cmd,exit=q.returncode,stdout=q.stdout,stderr=q.stderr))
 term.append(dict(stage=s['name'],readbacks=reads))
 rows.append(dict(stage=s['name'],test=s['test'],status='accepted first attempt' if i<6 else 'observer accounting refusal; raw test pass is not accepted',unit=r['authenticated_service']['unit'],main_process=r['authenticated_service']['main_process'],observer_error=r['observer_error'],wrapper_exit_code=r['wrapper_exit_code'],accounting_complete=r['accounting_complete'],accounting=r['final_accounting'] if i<6 else r['refusal_final_accounting'],wall_seconds=r['elapsed_seconds'],result_sha256=sha(o/'result.json'),stdout_sha256=sha(o/'stdout'),stderr_sha256=sha(o/'stderr'),stdout_bytes=(o/'stdout').stat().st_size,stderr_bytes=(o/'stderr').stat().st_size,admission_sha256=sha(s['admission_record'])))
for s in p['stages'][7:]:assert not Path(s['out']).exists() and not (d/'run-1'/f"{s['name']}-dispatch.json").exists()
def write(path,v):
 with path.open('x') as out:json.dump(v,out,indent=2);out.write('\n')
write(d/'TERMINAL.json',term);f['check_inputs'](p)
result=dict(status='incomplete after observer refusal',head=p['source_head'],plan_sha256=sha(d/'plan.json'),caller_sha256=sha(d/'launch.py'),launch_sha256=sha(d/'run-1/launch.json'),source_binding_sha256=sha(p['source_binding']),accepted_first_attempts=6,refused=1,unexecuted=15,rows=rows,remaining_tests=[s['test'] for s in p['stages'][7:]],terminal_sha256=sha(d/'TERMINAL.json'),full_source_and_inputs_match=True,input_count=len(p['inputs']),exact_enodev_source='Not identifiable from retained record: observer records exception type/message but no traceback or failing operation. Initial seven RefUnit calls returned -2; no recorded systemd call returned -19. Error occurred before final_report assignment, after 41 successful live samples. read_usage cpu.stat/cgroup.procs and other loop operations are source candidates, not proven origin.')
write(d/'RESULT.json',result)
with (d/'REPORT.md').open('x') as out:out.write('The first six original static methods are accepted first attempts. Stage 07, leader_exit::later_group_exit_preserves_worker_tool, remains an accounting refusal. Its exact named test printed 1 passed / 287 filtered, and both payload and admitted child returned 0, but observer_error is OSError: [Errno 19] No such device, accounting_complete is false and final_accounting is null. The final 15 stages were never dispatched.\n\nThe original observer retained refusal_final_accounting with 0.327610 CPU seconds, exact original PID 1747494 / start timestamp 1828976183558, exit status 0 and empty service. Observed wall was 1.089347181 seconds. Later fresh queries show inactive/empty and no loaded unit; they cannot reconstruct CPU themselves. This recovered accounting is retained separately and does not convert the refusal into an accepted result.\n\nThe exact ENODEV operation is not identifiable: the retained exception has no traceback, and all recorded systemd calls succeeded apart from seven initial RefUnit -2 results. The failure precedes final_report assignment and follows 41 successful samples. The cgroup-read loop is a source candidate, not a measured root cause. No observer change or inference of guest failure is made.\n\nAll seven services have two fresh inactive/empty readbacks. Full committed source, all 175 inputs, actual emitted ELF and hardware admission checks still match. No retry has run. Root has authorized one fresh unchanged stage 07, with its result recorded as a retry, followed by original stages 08–22 only if accepted. Six accepted first attempts will not be repeated.\n')
print(json.dumps({'RESULT':sha(d/'RESULT.json'),'REPORT':sha(d/'REPORT.md'),'TERMINAL':sha(d/'TERMINAL.json')}))
