load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("hermit")

rust_binary(
    name = "chrome-trace",
    srcs = glob([
        "chrome-trace/**/*.rs",
    ]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:tokio",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-ptrace",
        "//hermetic_infra/reverie:reverie-util",
    ],
)

rust_binary(
    name = "counter1",
    srcs = [
        "counter1.rs",
    ],
    deps = [
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-ptrace",
        "//hermetic_infra/reverie:reverie-util",
    ],
)

rust_binary(
    name = "counter2",
    srcs = [
        "counter2.rs",
    ],
    deps = [
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-ptrace",
        "//hermetic_infra/reverie:reverie-util",
    ],
)

rust_binary(
    name = "noop",
    srcs = [
        "noop.rs",
    ],
    autocargo = {
        # Only one rule is allowed to specify `cargo_toml_config`. This target
        # is as good as any.
        "cargo_toml_config": {
            "package": {
                "name": "reverie-examples",
                # Do not publish examples.
                "publish": False,
            },
        },
    },
    deps = [
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:tokio",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-ptrace",
        "//hermetic_infra/reverie:reverie-util",
    ],
)

rust_binary(
    name = "chunky_print",
    srcs = [
        "chunky_print.rs",
    ],
    deps = [
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-ptrace",
        "//hermetic_infra/reverie:reverie-util",
    ],
)

rust_binary(
    name = "strace",
    srcs = glob([
        "strace/**/*.rs",
    ]),
    deps = [
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-ptrace",
        "//hermetic_infra/reverie:reverie-util",
    ],
)

rust_binary(
    name = "strace_minimal",
    srcs = [
        "strace_minimal.rs",
    ],
    deps = [
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:tokio",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-ptrace",
        "//hermetic_infra/reverie:reverie-util",
    ],
)

rust_binary(
    name = "chaos",
    srcs = [
        "chaos.rs",
    ],
    deps = [
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-ptrace",
        "//hermetic_infra/reverie:reverie-util",
    ],
)

rust_binary(
    name = "debug",
    srcs = [
        "debug.rs",
    ],
    deps = [
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:tokio",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-ptrace",
        "//hermetic_infra/reverie:reverie-util",
    ],
)
