from pathlib import Path
import json,hashlib,os,stat
R=Path(__file__).resolve().parents[2];D=Path(__file__).resolve().parent;F=D/'frozen-v1';Q=D/'qualification-v2'
def rec(p):
 p=Path(p);b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
results=json.loads((F/'RESULTS.json').read_text());phases=results['phases'];by={x['name']:x for x in phases}
report='''The inactive backend prerequisite is implemented and qualified as a finite component on Reverie 000c15a1161ea2d58749431b5ddaaa97f7aa37d5. All 59 selected declarations passed: seven new private-publication unit tests, 43 unchanged library neighbors, and nine unchanged real VM declarations. Format, core/ptrace check, and selected-crate Clippy with -D warnings passed. This is authored evidence awaiting independent source/runtime review; no SCM or publication action occurred.

SOURCE.patch is the complete three-path change, including the new process_signal_publication.rs. Full current source is copied under source/ and bound by FULL-SOURCE-MANIFEST.json (2,621 entries including three unexpanded gitlinks); the actual ignored Cargo.lock is separately bound. Before files and exact patch reconstruction are retained. V1-TO-V2.patch preserves the substantive file-drop correction; V2-TO-V3.patch removes two unused readiness wrappers after the first compile warning refusal. All seven new test bodies and every selected existing test remain in the complete source copy.

The private registry holds weak per-process/current-image bindings; executors hold the live binding, threads share it, fork registers a fresh exact process generation and parent, and exec refreshes the image and authoritative descriptor/signal backing. Publication revalidates the exact live generation and image after acquiring the authoritative file table and shared signal transaction. Retirement prevents stale publication; retaining a control keeps no executor, descriptor or GlobalState alive. No GlobalTool installation hook or other public API was added.

The per-process transaction serializes existing pending mutation with signalfd readiness, including producers, all three consumers, ignored-disposition flushing, signalfd alias changes, fork/exec, frame-mask state and retirement. Final replaced guest descriptor/table drops are deferred until the transaction is released. Ordinary I/O and Tool hooks do not run under that transaction. The fresh unchanged VM controls exercise the live default/plain and Tool paths; earlier runs were not inherited as current evidence.

The new entry points remain deliberately inactive. Exactly three item-level cfg_attr(not(test), expect(dead_code, reason = ...)) annotations explain control creation and the two unused private entry points. Their bodies are compiled and pass the unchanged production warning gate. There is no production new publisher, scheduler/child-completion caller, selector, ToolControlled activation, receiver admission or wake/resume action. The private failure latch retains an actual post-insertion readiness failure and rejects later private publication; it does not notify G or terminate the driver. Activation still requires the separate owner terminal protocol. Child input has no production constructor: exact registered parent/generation and exit status are checked, but a future staging producer must authenticate UID/CPU provenance and preserve waitability ordering. Tests provide explicit fixture accounting. No killed/orphan child guarantee is added.

First failure is preserved: the initial compiler returned raw0 with two obsolete private wrappers warning in each library build. The unchanged result parser rejected it (accepted=false), terminal/source accounting succeeded, and both emitted ELFs are retained under qualification-v1/retained-unqualified-binaries. The wrappers had no remaining callers; removing them did not alter an assertion, selector or lint gate. Corrected qualification-v2 has fresh plans/metadata/dependency binding and separately retained lib/static ELFs. Historical compiler paths in receipts identify cache locations at execution time; retained copies and their BINDING.json preserve the actual bytes after later cache reuse.

Goalpost check: no existing assertion, tolerance, comparator, exception, label, count check or budget was weakened/deleted. New tests are additive; original selected tests are base-identical. Count discovery is actual (495 library, 304 static declarations), not an assumed increment. No fixed affected count consumer required an edit. No Hermit timer repair, composed scheduling design, descriptor-width repair, confirmed stale-OFD fix, imported-FIFO cancellation, full-suite or full-DAG success is claimed.

Evidence preparation retained one additional failed check: Git apply from a nested repository directory returned0 while skipping root-relative paths; the exact after-byte assertion rejected that reconstruction. RECONSTRUCTION.json retains this, and the separate patch-tool reconstruction then matched all three files. This never changed live product bytes or test results. The reviewed caller/parser/observer were unchanged; the dependency binder changed only directory depth from its established recipe.
'''
(F/'REPORT.md').write_text(report)
rows=[]
for label,names in [('Compile',['compile']),('Format',['format']),('Lists',['list-lib','list-static']),('New unit controls',[f'test-{i:02}'for i in range(1,8)]),('Unchanged library controls',[f'test-{i:02}'for i in range(8,51)]),('Unchanged VM controls',[f'vm-{i:02}'for i in range(1,10)]),('Core + ptrace',['core-check']),('Clippy',['clippy'])]:
 selected=[by[n]for n in names];rows.append(f"| {label} | {len(names)} | {sum(x['cpu_seconds']for x in selected):.3f} | {sum(x['observed_wall_seconds']for x in selected):.3f} |")
text='''Exact qualification is recorded in RESULTS.json, with each plan, actual outcome, raw stdout/stderr, source continuity and terminal accounting. All 66 corrected phases qualified; metadata is included in that count. Each test declaration ran once, exact selected count1, no ignored/measured/failed tests, and REVERIE_REQUIRE_KVM=1. Current component inventories:495 lib and304 static; selected50 and9 respectively. No discovered-but-unexecuted case is a pass.

| Phase group | Phases | Aggregate CPU seconds | Sum of observed wall seconds |
|---|---:|---:|---:|
'''+ '\n'.join(rows)+f"\n\nCorrected phase total including metadata: {results['total_cpu_seconds']:.3f} aggregate CPU seconds and {results['total_observed_wall_seconds']:.3f} summed observer wall seconds. These include source/accounting verification overhead; actual harness execution times and payload times remain separately retained in each result. Original unqualified compile: {results['first_attempt']['cpu_seconds']:.3f} CPU seconds and {results['first_attempt']['observed_wall_seconds']:.3f} observer wall seconds. Its preceding metadata passed; no original-source tests ran. Across both preparations there were68 actual phase attempts,67 qualified and one diagnostic refusal.\n\n"+'''The nine actual VM declaration passes retain their original internal loops. Source-derived executions are separate from Rust counts: parked modes0..14 plus16,17,18,19 (19 KVM instances); sibling ten modes in plain and Tool configurations (20 KVM and ten native references); fork/thread exec lifetime two configurations each (four KVM); one signalfd KVM/native pair with its unchanged internal five-shape/thirteen-flag comparisons. Thus the completed test bodies contain44 KVM instances and11 native references. This is a source-derived breakdown of the passing declarations, not44 separately observed receipts or a wider population claim. Existing30-second inner child deadlines are unchanged.

Limits exactly per approved phase: metadata/compile/core/Clippy600 aggregate CPU seconds/900 wall; format/lists/each exact declaration30/60. All16GiB memory,zero swap,16MiBstderr,64MiBmaintainedstdout,16MiBreadback and100GiBfreefloor. Pinned nightly2026-07-29; offline/locked Cargo; two Cargo/third-party jobs. Original observer137c9b42 and lease protocol unchanged. Fresh metadata resolves288 workspace packages; KVM closure155packages with7,083 freshly hashed external files/170,540,804 bytes/zero dependency symlinks. All source/SCM/helper identities are checked before and after each phase. Only the owned target was reused, no foreign cache copied.

Qualified ELF hashes: lib d099437c50c217b1ae61af2278c6350a4cf96740d4169e47feefe277575ba3b4; static90eff37c7e030272481c0ef4c7406e36f88320f4b2a3a90e5981d00a22bf160f. Immutable copies are in qualification-v2/retained-binaries. Compiler JSON, exact target/kind/profile, retained-copy identities, ELF loader queries, actual list output and each exact test result are all bound. The cache filenames may later be reused; the historical record is not a claim those mutable paths retain old bytes forever.

All phase-owned lease descriptors are closed. LEASE-RELEASE.json records a successful nonblocking exclusive availability check, immediately released without state mutation. Product/HEAD/index remain fixed for independent review. No source, compiler or test failure is hidden by that lifecycle check.
'''
(F/'QUALIFICATION.md').write_text(text)
# Bind stable source/evidence, never current contents of historical mutable compiler paths.
inputs={}
for root in [F,D/'prequalification-v1',D/'prequalification-v2',D/'prequalification-v3',D/'qualification-v1',Q]:
 for p in sorted(root.rglob('*')):
  if any(x in ('tmp','cache')for x in p.relative_to(root).parts):continue
  if p.is_symlink():continue
  if p.is_file():inputs[str(p)]=rec(p)
for p in [D/'freeze-final.py',D/'finish-freeze-final.py',D/'final-reports.py']:
 inputs[str(p)]=rec(p)
(F/'INPUTS.json').write_text(json.dumps(list(inputs.values()),indent=2)+'\n')
readback=[rec(F/n)for n in ['REPORT.md','QUALIFICATION.md','RESULTS.json','SOURCE.patch','V1-TO-V2.patch','V2-TO-V3.patch','SOURCE_INPUTS.json','FULL-SOURCE-MANIFEST.json','CALLER_INPUTS.json','RECONSTRUCTION.json','LEASE-RELEASE.json','INPUTS.json']]
(F/'READBACK.json').write_text(json.dumps(readback,indent=2)+'\n')
(F/'TARGET.json').write_text(json.dumps({'base':'000c15a1161ea2d58749431b5ddaaa97f7aa37d5','scope':'Inactive backend-private process publication prerequisite; actual implementation review, not activation approval','report':rec(F/'REPORT.md'),'qualification':rec(F/'QUALIFICATION.md'),'source':rec(F/'SOURCE.patch'),'input_manifest':rec(F/'INPUTS.json'),'readback':rec(F/'READBACK.json'),'input_count':len(inputs),'no_product_or_SCM_mutation_after_freeze':True},indent=2)+'\n')
print(json.dumps({n:rec(F/n)for n in ['REPORT.md','QUALIFICATION.md','RESULTS.json','INPUTS.json','READBACK.json','TARGET.json']},indent=2))
