[package]
name = "reverie-narf"
description = "First-class Narf kernel backend for arbitrary Reverie tools"
version = "0.2.0"
authors = ["Meta Platforms"]
edition = "2024"
repository = "https://github.com/facebookexperimental/reverie"
license = "BSD-2-Clause"

[dependencies]
async-trait = "0.1.86"
libc = "0.2.186"
reverie = { package = "reverie-core", version = "0.2.0", path = "../reverie" }
reverie-memory = { version = "0.2.0", path = "../reverie-memory" }
reverie-narf-core = { version = "0.2.0", path = "../reverie-narf-core" }
reverie-syscalls = { version = "0.2.0", path = "../reverie-syscalls" }

[dev-dependencies]
futures = { version = "0.3.31", features = ["executor"] }
