[package]
name = "reverie-elf-loader"
version = "0.4.1"
authors = ["Meta Platforms"]
edition = "2024"
repository = "https://github.com/facebookexperimental/reverie"
license = "BSD-2-Clause"
readme = "README.md"
homepage = "https://hermetic-infra.org"
documentation = "https://docs.rs/reverie-elf-loader"
keywords = ["linux", "instrumentation", "hermit"]
categories = ["development-tools::debugging", "os::linux-apis"]
description = "Standalone, unwired x86-64 Linux ELF start preparation and freestanding loader"
build = "build.rs"

[dependencies]
libc = "0.2.186"

[dev-dependencies]
sha2 = "0.10.9"
reverie-inguest = { path = "../reverie-inguest", default-features = false, features = ["rcb-clock", "coordinator-rpc"] }
reverie-ptrace = { path = "../reverie-ptrace" }
reverie = { package = "reverie-core", path = "../reverie" }
