load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("hermit")

rust_binary(
    name = "scrape-syscalls",
    srcs = glob(["scrape-syscalls/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:goblin",
        "fbsource//third-party/rust:libc",
        "fbsource//third-party/rust:nix",
        "fbsource//third-party/rust:scroll",
    ],
)
