/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

//! Prints reverie-syscalls' `src/nix_shim.rs` from the host's nix.
//!
//! Every flag table is nix's own `bitflags::Flags::FLAGS`, in order. Run
//! through `../regen.sh`.

use std::fmt::Display;
use std::fmt::LowerHex;

use bitflags::Flags;

const HEADER: &str = r#"// @generated by reverie-syscalls/shim-gen/regen.sh from nix 0.30.1
// (x86_64-unknown-linux-gnu). Do not edit by hand: regenerate, then run the
// reverie-syscalls host tests, which check every item here against `nix`.

//! The `nix` types that reverie-syscalls names, for builds without `std`.
//!
//! nix requires `std`. With `std` off, this module stands in for nix under the
//! same paths (`crate::nix::fcntl::OFlag` and so on). Each flags type is
//! declared with the `bitflags` crate nix uses, the derives nix's
//! `libc_bitflags!` uses, and nix's own flag table in order, so values, names
//! and `Debug` output are nix's. The tests at the end of this file check that
//! against nix on the host.

#![allow(missing_docs)]

pub mod unistd {
    use core::fmt;

    use crate::libc::pid_t;

    /// Look-alike of `nix::unistd::Pid`, without the calls into the host
    /// (`this`, `parent`).
    #[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
    pub struct Pid(pid_t);

    impl Pid {
        /// Creates `Pid` from raw `pid_t`.
        pub const fn from_raw(pid: pid_t) -> Self {
            Pid(pid)
        }

        /// Returns PID's raw `pid_t`.
        pub const fn as_raw(self) -> pid_t {
            self.0
        }
    }

    impl From<Pid> for pid_t {
        fn from(pid: Pid) -> Self {
            pid.0
        }
    }

    impl fmt::Display for Pid {
        fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
            fmt::Display::fmt(&self.0, f)
        }
    }
}
"#;

const TESTS: &str = r#"
#[cfg(all(test, feature = "std"))]
mod tests {
    use core::fmt::Debug;

    use bitflags::Bits;
    use bitflags::Flags;

    /// `A` must have `B`'s flag table (names and values, in order) and the
    /// same `Debug` output for every flag, for no flags, for all bits, and
    /// for all known flags.
    fn same_flags<A, B, X>()
    where
        A: Flags<Bits = X> + Debug,
        B: Flags<Bits = X> + Debug,
        X: Bits + Debug + PartialEq,
    {
        let ours: Vec<(&str, X)> = A::FLAGS
            .iter()
            .map(|f| (f.name(), f.value().bits()))
            .collect();
        let theirs: Vec<(&str, X)> = B::FLAGS
            .iter()
            .map(|f| (f.name(), f.value().bits()))
            .collect();
        assert_eq!(ours, theirs);
        let mut samples: Vec<X> = ours.iter().map(|&(_, bits)| bits).collect();
        samples.extend([X::EMPTY, X::ALL, A::all().bits()]);
        for bits in samples {
            assert_eq!(
                format!("{:?}", A::from_bits_retain(bits)),
                format!("{:?}", B::from_bits_retain(bits)),
            );
        }
    }

    #[test]
    fn flags_match_nix() {
        same_flags::<super::fcntl::OFlag, nix::fcntl::OFlag, _>();
        same_flags::<super::fcntl::AtFlags, nix::fcntl::AtFlags, _>();
        same_flags::<super::sched::CloneFlags, nix::sched::CloneFlags, _>();
        same_flags::<super::sys::epoll::EpollCreateFlags, nix::sys::epoll::EpollCreateFlags, _>();
        same_flags::<super::sys::eventfd::EfdFlags, nix::sys::eventfd::EfdFlags, _>();
        same_flags::<super::sys::inotify::InitFlags, nix::sys::inotify::InitFlags, _>();
        same_flags::<super::sys::mman::MapFlags, nix::sys::mman::MapFlags, _>();
        same_flags::<super::sys::mman::ProtFlags, nix::sys::mman::ProtFlags, _>();
        same_flags::<super::sys::signalfd::SfdFlags, nix::sys::signalfd::SfdFlags, _>();
        same_flags::<super::sys::socket::SockFlag, nix::sys::socket::SockFlag, _>();
        same_flags::<super::sys::stat::Mode, nix::sys::stat::Mode, _>();
        same_flags::<super::sys::stat::SFlag, nix::sys::stat::SFlag, _>();
        same_flags::<super::sys::timerfd::TimerFlags, nix::sys::timerfd::TimerFlags, _>();
        same_flags::<super::sys::wait::WaitPidFlag, nix::sys::wait::WaitPidFlag, _>();
    }

    #[test]
    fn pid_matches_nix() {
        for raw in [i32::MIN, -1, 0, 1, 42, i32::MAX] {
            let ours = super::unistd::Pid::from_raw(raw);
            let theirs = nix::unistd::Pid::from_raw(raw);
            assert_eq!(ours.as_raw(), theirs.as_raw());
            assert_eq!(i32::from(ours), i32::from(theirs));
            assert_eq!(format!("{ours}"), format!("{theirs}"));
            assert_eq!(format!("{ours:?}"), format!("{theirs:?}"));
        }
    }
}
"#;

fn emit<F: Flags>(ty: &str, repr: &str, path: &str)
where
    F::Bits: LowerHex + Display,
{
    println!("    bitflags::bitflags! {{");
    println!("        /// Look-alike of `nix::{path}::{ty}`.");
    println!("        #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]");
    println!("        #[repr(transparent)]");
    println!("        pub struct {ty}: {repr} {{");
    for f in F::FLAGS {
        let bits = f.value().bits();
        // Negative values are written in decimal: a hex literal would overflow.
        let lit = if bits.to_string().starts_with('-') {
            bits.to_string()
        } else {
            format!("{bits:#x}")
        };
        println!("            const {} = {lit};", f.name());
    }
    println!("        }}");
    println!("    }}");
}

macro_rules! module {
    ($name:literal, $path:literal, $( $ty:ident : $repr:ty = $real:ty ),+ $(,)?) => {
        println!("pub mod {} {{", $name);
        $(
            // Compile-time guard: the declared repr is nix's.
            let _: fn($real) -> $repr = |f| f.bits();
            emit::<$real>(stringify!($ty), stringify!($repr), $path);
        )+
        println!("}}");
    };
}

fn main() {
    print!("{HEADER}");
    println!();
    module!("fcntl", "fcntl",
        OFlag: i32 = nix::fcntl::OFlag,
        AtFlags: i32 = nix::fcntl::AtFlags);
    module!("sched", "sched",
        CloneFlags: i32 = nix::sched::CloneFlags);
    println!("pub mod sys {{");
    module!("epoll", "sys::epoll",
        EpollCreateFlags: i32 = nix::sys::epoll::EpollCreateFlags);
    module!("eventfd", "sys::eventfd",
        EfdFlags: i32 = nix::sys::eventfd::EfdFlags);
    module!("inotify", "sys::inotify",
        InitFlags: i32 = nix::sys::inotify::InitFlags);
    module!("mman", "sys::mman",
        MapFlags: i32 = nix::sys::mman::MapFlags,
        ProtFlags: i32 = nix::sys::mman::ProtFlags);
    module!("signalfd", "sys::signalfd",
        SfdFlags: i32 = nix::sys::signalfd::SfdFlags);
    module!("socket", "sys::socket",
        SockFlag: i32 = nix::sys::socket::SockFlag);
    module!("stat", "sys::stat",
        Mode: u32 = nix::sys::stat::Mode,
        SFlag: u32 = nix::sys::stat::SFlag);
    module!("timerfd", "sys::timerfd",
        TimerFlags: i32 = nix::sys::timerfd::TimerFlags);
    module!("wait", "sys::wait",
        WaitPidFlag: i32 = nix::sys::wait::WaitPidFlag);
    println!("}}");
    print!("{TESTS}");
}
