[package]
name = "reverie-tool-sysctr"
version = "0.1.0"
authors = ["Meta Platforms"]
edition = "2024"
repository = "https://github.com/facebookexperimental/reverie"
license = "BSD-2-Clause"
publish = false

[dependencies]
reverie = { version = "0.1.0", path = "../reverie" }
serde = { version = "1.0.219", features = ["derive"] }
