// @generated by reverie-syscalls/shim-gen/regen.sh from libc 0.2.189
// (x86_64-unknown-linux-gnu, `-Zunpretty=expanded`). Do not edit by hand:
// regenerate, then run the reverie-syscalls host tests, which check every item
// here against `libc`.

//! The subset of `libc` that reverie-syscalls names, for builds without
//! `std`.
//!
//! On `target_os = "none"` the `libc` crate is empty. Guest memory is still
//! Linux memory, so the syscall argument types must keep glibc's x86_64
//! layouts exactly. These definitions are libc's own, copied verbatim. The
//! tests at the end of this file check, against `libc` on the host, that every
//! typedef is the same type, every constant has the same type and value, and
//! every struct has the same size, alignment, and public field offsets and
//! sizes.
//!
//! Each struct derives exactly the standard traits libc implements for it.
//! libc writes `PartialEq`/`Eq`/`Hash` by hand for `epoll_event` and
//! `sigevent`; its versions compare and hash every non-padding field, which is
//! what the derives here do, since `Padding` always compares equal and hashes
//! to nothing.

#![allow(non_camel_case_types)]
#![allow(missing_docs)]
// libc's text is copied verbatim; `FD_SETSIZE as usize` is a no-op cast on
// x86_64 that libc keeps for other targets.
#![allow(clippy::unnecessary_cast)]

pub use core::ffi::c_char;
pub use core::ffi::c_double;
pub use core::ffi::c_float;
pub use core::ffi::c_int;
pub use core::ffi::c_long;
pub use core::ffi::c_longlong;
pub use core::ffi::c_schar;
pub use core::ffi::c_short;
pub use core::ffi::c_uchar;
pub use core::ffi::c_uint;
pub use core::ffi::c_ulong;
pub use core::ffi::c_ulonglong;
pub use core::ffi::c_ushort;
pub use core::ffi::c_void;
use core::mem::MaybeUninit;

/// libc's padding wrapper: uninitialized bytes that compare equal, hash to
/// nothing, and default to zero.
#[repr(transparent)]
#[derive(Clone, Copy)]
pub(crate) struct Padding<T: Copy>(MaybeUninit<T>);

impl<T: Copy> Default for Padding<T> {
    fn default() -> Self {
        Self(MaybeUninit::zeroed())
    }
}

impl<T: Copy> core::fmt::Debug for Padding<T> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let full_name = core::any::type_name::<Self>();
        let prefix_len = full_name.find("Padding").unwrap();
        f.pad(&full_name[prefix_len..])
    }
}

impl<T: Copy> core::hash::Hash for Padding<T> {
    fn hash<H: core::hash::Hasher>(&self, _state: &mut H) {}
}

impl<T: Copy> PartialEq for Padding<T> {
    fn eq(&self, _other: &Self) -> bool {
        true
    }
}

impl<T: Copy> Eq for Padding<T> {}

pub type __fsword_t = i64;

pub type __s32 = c_int;

pub type __s64 = c_longlong;

pub type __u16 = c_ushort;

pub type __u32 = c_uint;

pub type __u64 = c_ulonglong;

pub type blkcnt64_t = i64;

pub type blkcnt_t = i64;

pub type blksize_t = i64;

pub type cc_t = c_uchar;

pub type clock_t = i64;

pub type clockid_t = c_int;

pub type dev_t = u64;

pub type fsblkcnt_t = u64;

pub type fsfilcnt_t = u64;

pub type gid_t = u32;

pub type id_t = c_uint;

pub type ino64_t = u64;

pub type ino_t = u64;

pub type key_t = c_int;

pub type loff_t = c_longlong;

pub type mode_t = u32;

pub type mqd_t = c_int;

pub type msglen_t = u64;

pub type msgqnum_t = u64;

pub type nfds_t = c_ulong;

pub type nlink_t = u64;

pub type off64_t = i64;

pub type off_t = i64;

pub type pid_t = i32;

pub type rlim64_t = u64;

pub type rlim_t = u64;

pub type sa_family_t = u16;

pub type shmatt_t = u64;

pub type sighandler_t = size_t;

pub type size_t = usize;

pub type socklen_t = u32;

pub type suseconds_t = i64;

pub type tcflag_t = c_uint;

pub type time_t = i64;

pub type uid_t = u32;

pub const AT_EGID: c_ulong = 14;

pub const AT_EUID: c_ulong = 12;

pub const AT_FDCWD: c_int = -100;

pub const AT_GID: c_ulong = 13;

pub const AT_RANDOM: c_ulong = 25;

pub const AT_REMOVEDIR: c_int = 0x200;

pub const AT_UID: c_ulong = 11;

pub const CLOCK_BOOTTIME: clockid_t = 7;

pub const CLOCK_BOOTTIME_ALARM: clockid_t = 9;

pub const CLOCK_MONOTONIC: clockid_t = 1;

pub const CLOCK_MONOTONIC_COARSE: clockid_t = 6;

pub const CLOCK_MONOTONIC_RAW: clockid_t = 4;

pub const CLOCK_PROCESS_CPUTIME_ID: clockid_t = 2;

pub const CLOCK_REALTIME: clockid_t = 0;

pub const CLOCK_REALTIME_ALARM: clockid_t = 8;

pub const CLOCK_REALTIME_COARSE: clockid_t = 5;

pub const CLOCK_THREAD_CPUTIME_ID: clockid_t = 3;

pub const CLONE_CHILD_CLEARTID: c_int = 0x200000;

pub const CLONE_CHILD_SETTID: c_int = 0x01000000;

pub const CLONE_DETACHED: c_int = 0x400000;

pub const CLONE_FILES: c_int = 0x400;

pub const CLONE_FS: c_int = 0x200;

pub const CLONE_IO: c_int = 0x80000000_u32 as c_int;

pub const CLONE_NEWCGROUP: c_int = 0x02000000;

pub const CLONE_NEWIPC: c_int = 0x08000000;

pub const CLONE_NEWNET: c_int = 0x40000000;

pub const CLONE_NEWNS: c_int = 0x20000;

pub const CLONE_NEWPID: c_int = 0x20000000;

pub const CLONE_NEWUSER: c_int = 0x10000000;

pub const CLONE_NEWUTS: c_int = 0x04000000;

pub const CLONE_PARENT: c_int = 0x8000;

pub const CLONE_PARENT_SETTID: c_int = 0x100000;

pub const CLONE_PTRACE: c_int = 0x2000;

pub const CLONE_SETTLS: c_int = 0x80000;

pub const CLONE_SIGHAND: c_int = 0x800;

pub const CLONE_SYSVSEM: c_int = 0x40000;

pub const CLONE_THREAD: c_int = 0x10000;

pub const CLONE_UNTRACED: c_int = 0x800000;

pub const CLONE_VFORK: c_int = 0x4000;

pub const CLONE_VM: c_int = 0x100;

pub const FD_SETSIZE: usize = 1024;

pub const F_DUPFD: c_int = 0;

pub const O_CREAT: c_int = 64;

pub const O_RDONLY: c_int = 0;

pub const O_TRUNC: c_int = 512;

pub const O_WRONLY: c_int = 1;

pub const POLLERR: c_short = 0x8;

pub const POLLHUP: c_short = 0x10;

pub const POLLIN: c_short = 0x1;

pub const POLLNVAL: c_short = 0x20;

pub const POLLOUT: c_short = 0x4;

pub const POLLPRI: c_short = 0x2;

pub const POLLRDBAND: c_short = 0x080;

pub const POLLRDNORM: c_short = 0x040;

pub const POLLWRBAND: c_short = 0x200;

pub const POLLWRNORM: c_short = 0x100;

pub const SEEK_CUR: c_int = 1;

pub const SEEK_DATA: c_int = 3;

pub const SEEK_END: c_int = 2;

pub const SEEK_HOLE: c_int = 4;

pub const SEEK_SET: c_int = 0;

pub const SIGALRM: c_int = 14;

pub const SIGCHLD: c_int = 17;

pub const SIGUSR1: c_int = 10;

pub const SIGUSR2: c_int = 12;

const ULONG_SIZE: usize = 64;

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct dirent {
    pub d_ino: ino_t,
    pub d_off: off_t,
    pub d_reclen: c_ushort,
    pub d_type: c_uchar,
    pub d_name: [c_char; 256],
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct dirent64 {
    pub d_ino: ino64_t,
    pub d_off: off64_t,
    pub d_reclen: c_ushort,
    pub d_type: c_uchar,
    pub d_name: [c_char; 256],
}

#[repr(C)]
#[repr(packed)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct epoll_event {
    pub events: u32,
    pub u64: u64,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct fd_set {
    fds_bits: [c_ulong; FD_SETSIZE as usize / ULONG_SIZE],
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct file_clone_range {
    pub src_fd: __s64,
    pub src_offset: __u64,
    pub src_length: __u64,
    pub dest_offset: __u64,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct flock {
    pub l_type: c_short,
    pub l_whence: c_short,
    pub l_start: off_t,
    pub l_len: off_t,
    pub l_pid: pid_t,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct flock64 {
    pub l_type: c_short,
    pub l_whence: c_short,
    pub l_start: off64_t,
    pub l_len: off64_t,
    pub l_pid: pid_t,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct fsid_t {
    __val: [c_int; 2],
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct iovec {
    pub iov_base: *mut c_void,
    pub iov_len: size_t,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct ipc_perm {
    pub __key: key_t,
    pub uid: uid_t,
    pub gid: gid_t,
    pub cuid: uid_t,
    pub cgid: gid_t,
    pub mode: c_ushort,
    __pad1: Padding<c_ushort>,
    pub __seq: c_ushort,
    __pad2: Padding<c_ushort>,
    __unused1: Padding<u64>,
    __unused2: Padding<u64>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct itimerspec {
    pub it_interval: timespec,
    pub it_value: timespec,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct itimerval {
    pub it_interval: timeval,
    pub it_value: timeval,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct mmsghdr {
    pub msg_hdr: msghdr,
    pub msg_len: c_uint,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct mq_attr {
    pub mq_flags: c_long,
    pub mq_maxmsg: c_long,
    pub mq_msgsize: c_long,
    pub mq_curmsgs: c_long,
    pad: Padding<[c_long; 4]>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct msghdr {
    pub msg_name: *mut c_void,
    pub msg_namelen: socklen_t,
    pub msg_iov: *mut iovec,
    pub msg_iovlen: size_t,
    pub msg_control: *mut c_void,
    pub msg_controllen: size_t,
    pub msg_flags: c_int,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct msqid_ds {
    pub msg_perm: ipc_perm,
    pub msg_stime: time_t,
    pub msg_rtime: time_t,
    pub msg_ctime: time_t,
    pub __msg_cbytes: u64,
    pub msg_qnum: msgqnum_t,
    pub msg_qbytes: msglen_t,
    pub msg_lspid: pid_t,
    pub msg_lrpid: pid_t,
    __glibc_reserved4: Padding<u64>,
    __glibc_reserved5: Padding<u64>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct pollfd {
    pub fd: c_int,
    pub events: c_short,
    pub revents: c_short,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct rlimit {
    pub rlim_cur: rlim_t,
    pub rlim_max: rlim_t,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct rlimit64 {
    pub rlim_cur: rlim64_t,
    pub rlim_max: rlim64_t,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct rusage {
    pub ru_utime: timeval,
    pub ru_stime: timeval,
    pub ru_maxrss: c_long,
    pub ru_ixrss: c_long,
    pub ru_idrss: c_long,
    pub ru_isrss: c_long,
    pub ru_minflt: c_long,
    pub ru_majflt: c_long,
    pub ru_nswap: c_long,
    pub ru_inblock: c_long,
    pub ru_oublock: c_long,
    pub ru_msgsnd: c_long,
    pub ru_msgrcv: c_long,
    pub ru_nsignals: c_long,
    pub ru_nvcsw: c_long,
    pub ru_nivcsw: c_long,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct sched_param {
    pub sched_priority: c_int,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct sembuf {
    pub sem_num: c_ushort,
    pub sem_op: c_short,
    pub sem_flg: c_short,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct shmid_ds {
    pub shm_perm: ipc_perm,
    pub shm_segsz: size_t,
    pub shm_atime: time_t,
    pub shm_dtime: time_t,
    pub shm_ctime: time_t,
    pub shm_cpid: pid_t,
    pub shm_lpid: pid_t,
    pub shm_nattch: shmatt_t,
    __unused4: Padding<u64>,
    __unused5: Padding<u64>,
}

#[repr(C)]
#[allow(unpredictable_function_pointer_comparisons)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct sigaction {
    pub sa_sigaction: sighandler_t,
    pub sa_mask: sigset_t,
    pub sa_flags: c_int,
    pub sa_restorer: Option<extern "C" fn()>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct sigevent {
    pub sigev_value: sigval,
    pub sigev_signo: c_int,
    pub sigev_notify: c_int,
    pub sigev_notify_thread_id: c_int,
    __unused1: Padding<[c_int; 11]>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct siginfo_t {
    pub si_signo: c_int,
    pub si_errno: c_int,
    pub si_code: c_int,
    #[doc(hidden)]
    #[deprecated(
        since = "0.2.54",
        note = "Please leave a comment on \
    https://github.com/rust-lang/libc/pull/1316 if you're using \
    this field"
    )]
    pub _pad: [c_int; 29],
    _align: [u64; 0],
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct sigset_t {
    __val: [u64; 16],
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct sigval {
    pub sival_ptr: *mut c_void,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct sockaddr {
    pub sa_family: sa_family_t,
    pub sa_data: [c_char; 14],
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct stack_t {
    pub ss_sp: *mut c_void,
    pub ss_flags: c_int,
    pub ss_size: size_t,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct stat {
    pub st_dev: dev_t,
    pub st_ino: ino_t,
    pub st_nlink: nlink_t,
    pub st_mode: mode_t,
    pub st_uid: uid_t,
    pub st_gid: gid_t,
    __pad0: Padding<c_int>,
    pub st_rdev: dev_t,
    pub st_size: off_t,
    pub st_blksize: blksize_t,
    pub st_blocks: blkcnt_t,
    pub st_atime: time_t,
    pub st_atime_nsec: i64,
    pub st_mtime: time_t,
    pub st_mtime_nsec: i64,
    pub st_ctime: time_t,
    pub st_ctime_nsec: i64,
    __unused: Padding<[i64; 3]>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct statfs {
    pub f_type: __fsword_t,
    pub f_bsize: __fsword_t,
    pub f_blocks: fsblkcnt_t,
    pub f_bfree: fsblkcnt_t,
    pub f_bavail: fsblkcnt_t,
    pub f_files: fsfilcnt_t,
    pub f_ffree: fsfilcnt_t,
    pub f_fsid: fsid_t,
    pub f_namelen: __fsword_t,
    pub f_frsize: __fsword_t,
    f_spare: [__fsword_t; 5],
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct statx {
    pub stx_mask: __u32,
    pub stx_blksize: __u32,
    pub stx_attributes: __u64,
    pub stx_nlink: __u32,
    pub stx_uid: __u32,
    pub stx_gid: __u32,
    pub stx_mode: __u16,
    __statx_pad1: Padding<[__u16; 1]>,
    pub stx_ino: __u64,
    pub stx_size: __u64,
    pub stx_blocks: __u64,
    pub stx_attributes_mask: __u64,
    pub stx_atime: statx_timestamp,
    pub stx_btime: statx_timestamp,
    pub stx_ctime: statx_timestamp,
    pub stx_mtime: statx_timestamp,
    pub stx_rdev_major: __u32,
    pub stx_rdev_minor: __u32,
    pub stx_dev_major: __u32,
    pub stx_dev_minor: __u32,
    pub stx_mnt_id: __u64,
    pub stx_dio_mem_align: __u32,
    pub stx_dio_offset_align: __u32,
    pub stx_subvol: __u64,
    pub stx_atomic_write_unit_min: __u32,
    pub stx_atomic_write_unit_max: __u32,
    pub stx_atomic_write_segments_max: __u32,
    pub stx_dio_read_offset_align: __u32,
    pub stx_atomic_write_unit_max_opt: __u32,
    __statx_pad2: Padding<[__u32; 1]>,
    __statx_pad3: Padding<[__u64; 8]>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct statx_timestamp {
    pub tv_sec: __s64,
    pub tv_nsec: __u32,
    __statx_timestamp_pad1: Padding<[__s32; 1]>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct sysinfo {
    pub uptime: i64,
    pub loads: [u64; 3],
    pub totalram: u64,
    pub freeram: u64,
    pub sharedram: u64,
    pub bufferram: u64,
    pub totalswap: u64,
    pub freeswap: u64,
    pub procs: c_ushort,
    pub pad: c_ushort,
    pub totalhigh: u64,
    pub freehigh: u64,
    pub mem_unit: c_uint,
    pub _f: [c_char; 0],
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct timespec {
    pub tv_sec: time_t,
    pub tv_nsec: c_long,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct timeval {
    pub tv_sec: time_t,
    pub tv_usec: suseconds_t,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct timex {
    pub modes: c_uint,
    pub offset: c_long,
    pub freq: c_long,
    pub maxerror: c_long,
    pub esterror: c_long,
    pub status: c_int,
    pub constant: c_long,
    pub precision: c_long,
    pub tolerance: c_long,
    pub time: timeval,
    pub tick: c_long,
    pub ppsfreq: c_long,
    pub jitter: c_long,
    pub shift: c_int,
    pub stabil: c_long,
    pub jitcnt: c_long,
    pub calcnt: c_long,
    pub errcnt: c_long,
    pub stbcnt: c_long,
    pub tai: c_int,
    pub __unused1: i32,
    pub __unused2: i32,
    pub __unused3: i32,
    pub __unused4: i32,
    pub __unused5: i32,
    pub __unused6: i32,
    pub __unused7: i32,
    pub __unused8: i32,
    pub __unused9: i32,
    pub __unused10: i32,
    pub __unused11: i32,
}

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct timezone {
    _data: (),
    _marker: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct tms {
    pub tms_utime: clock_t,
    pub tms_stime: clock_t,
    pub tms_cutime: clock_t,
    pub tms_cstime: clock_t,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct user_regs_struct {
    pub r15: c_ulonglong,
    pub r14: c_ulonglong,
    pub r13: c_ulonglong,
    pub r12: c_ulonglong,
    pub rbp: c_ulonglong,
    pub rbx: c_ulonglong,
    pub r11: c_ulonglong,
    pub r10: c_ulonglong,
    pub r9: c_ulonglong,
    pub r8: c_ulonglong,
    pub rax: c_ulonglong,
    pub rcx: c_ulonglong,
    pub rdx: c_ulonglong,
    pub rsi: c_ulonglong,
    pub rdi: c_ulonglong,
    pub orig_rax: c_ulonglong,
    pub rip: c_ulonglong,
    pub cs: c_ulonglong,
    pub eflags: c_ulonglong,
    pub rsp: c_ulonglong,
    pub ss: c_ulonglong,
    pub fs_base: c_ulonglong,
    pub gs_base: c_ulonglong,
    pub ds: c_ulonglong,
    pub es: c_ulonglong,
    pub fs: c_ulonglong,
    pub gs: c_ulonglong,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct utimbuf {
    pub actime: time_t,
    pub modtime: time_t,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct utsname {
    pub sysname: [c_char; 65],
    pub nodename: [c_char; 65],
    pub release: [c_char; 65],
    pub version: [c_char; 65],
    pub machine: [c_char; 65],
    pub domainname: [c_char; 65],
}

#[cfg(all(test, feature = "std"))]
mod tests {
    use core::mem::align_of;
    use core::mem::offset_of;
    use core::mem::size_of;

    fn field_size<T, F>(_: fn(&T) -> &F) -> usize {
        size_of::<F>()
    }

    /// Size and alignment, then each public field's offset and (unless the
    /// struct is packed, where fields cannot be borrowed) size.
    macro_rules! same_struct {
        ($name:ident $(, $field:ident)* $(,)?) => {
            same_struct!(@layout $name $(, $field)*);
            $(
                assert_eq!(
                    field_size(|s: &super::$name| &s.$field),
                    field_size(|s: &::libc::$name| &s.$field),
                    concat!("size of ", stringify!($name), ".", stringify!($field)),
                );
            )*
        };
        (packed $name:ident $(, $field:ident)* $(,)?) => {
            same_struct!(@layout $name $(, $field)*);
        };
        (@layout $name:ident $(, $field:ident)*) => {
            assert_eq!(
                size_of::<super::$name>(),
                size_of::<::libc::$name>(),
                concat!("size of ", stringify!($name)),
            );
            assert_eq!(
                align_of::<super::$name>(),
                align_of::<::libc::$name>(),
                concat!("alignment of ", stringify!($name)),
            );
            $(
                assert_eq!(
                    offset_of!(super::$name, $field),
                    offset_of!(::libc::$name, $field),
                    concat!("offset of ", stringify!($name), ".", stringify!($field)),
                );
            )*
        };
    }

    /// Each typedef must be the same type as libc's: the identity function
    /// only type-checks if it is.
    #[test]
    fn typedefs_match_libc() {
        macro_rules! same_type {
            ($($name:ident),* $(,)?) => {
                $(let _: fn(super::$name) -> ::libc::$name = |x| x;)*
            };
        }
        same_type!(
            __fsword_t,
            __s32,
            __s64,
            __u16,
            __u32,
            __u64,
            blkcnt64_t,
            blkcnt_t,
            blksize_t,
            cc_t,
            clock_t,
            clockid_t,
            dev_t,
            fsblkcnt_t,
            fsfilcnt_t,
            gid_t,
            id_t,
            ino64_t,
            ino_t,
            key_t,
            loff_t,
            mode_t,
            mqd_t,
            msglen_t,
            msgqnum_t,
            nfds_t,
            nlink_t,
            off64_t,
            off_t,
            pid_t,
            rlim64_t,
            rlim_t,
            sa_family_t,
            shmatt_t,
            sighandler_t,
            size_t,
            socklen_t,
            suseconds_t,
            tcflag_t,
            time_t,
            uid_t,
        );
    }

    /// Each constant must have libc's type and value.
    #[test]
    fn constants_match_libc() {
        macro_rules! same_const {
            ($($name:ident),* $(,)?) => {
                $(assert_eq!(super::$name, ::libc::$name, stringify!($name));)*
            };
        }
        same_const!(
            AT_EGID,
            AT_EUID,
            AT_FDCWD,
            AT_GID,
            AT_RANDOM,
            AT_REMOVEDIR,
            AT_UID,
            CLOCK_BOOTTIME,
            CLOCK_BOOTTIME_ALARM,
            CLOCK_MONOTONIC,
            CLOCK_MONOTONIC_COARSE,
            CLOCK_MONOTONIC_RAW,
            CLOCK_PROCESS_CPUTIME_ID,
            CLOCK_REALTIME,
            CLOCK_REALTIME_ALARM,
            CLOCK_REALTIME_COARSE,
            CLOCK_THREAD_CPUTIME_ID,
            CLONE_CHILD_CLEARTID,
            CLONE_CHILD_SETTID,
            CLONE_DETACHED,
            CLONE_FILES,
            CLONE_FS,
            CLONE_IO,
            CLONE_NEWCGROUP,
            CLONE_NEWIPC,
            CLONE_NEWNET,
            CLONE_NEWNS,
            CLONE_NEWPID,
            CLONE_NEWUSER,
            CLONE_NEWUTS,
            CLONE_PARENT,
            CLONE_PARENT_SETTID,
            CLONE_PTRACE,
            CLONE_SETTLS,
            CLONE_SIGHAND,
            CLONE_SYSVSEM,
            CLONE_THREAD,
            CLONE_UNTRACED,
            CLONE_VFORK,
            CLONE_VM,
            FD_SETSIZE,
            F_DUPFD,
            O_CREAT,
            O_RDONLY,
            O_TRUNC,
            O_WRONLY,
            POLLERR,
            POLLHUP,
            POLLIN,
            POLLNVAL,
            POLLOUT,
            POLLPRI,
            POLLRDBAND,
            POLLRDNORM,
            POLLWRBAND,
            POLLWRNORM,
            SEEK_CUR,
            SEEK_DATA,
            SEEK_END,
            SEEK_HOLE,
            SEEK_SET,
            SIGALRM,
            SIGCHLD,
            SIGUSR1,
            SIGUSR2,
        );
    }

    /// Each struct must have libc's layout.
    #[test]
    #[allow(deprecated)] // siginfo_t::_pad is deprecated in libc too.
    fn structs_match_libc() {
        same_struct!(dirent, d_ino, d_off, d_reclen, d_type, d_name);
        same_struct!(dirent64, d_ino, d_off, d_reclen, d_type, d_name);
        same_struct!(packed epoll_event, events, u64);
        // `fd_set` has no public fields.
        same_struct!(fd_set);
        same_struct!(
            file_clone_range,
            src_fd,
            src_offset,
            src_length,
            dest_offset
        );
        same_struct!(flock, l_type, l_whence, l_start, l_len, l_pid);
        same_struct!(flock64, l_type, l_whence, l_start, l_len, l_pid);
        // `fsid_t` has no public fields.
        same_struct!(fsid_t);
        same_struct!(iovec, iov_base, iov_len);
        same_struct!(ipc_perm, __key, uid, gid, cuid, cgid, mode, __seq);
        same_struct!(itimerspec, it_interval, it_value);
        same_struct!(itimerval, it_interval, it_value);
        same_struct!(mmsghdr, msg_hdr, msg_len);
        same_struct!(mq_attr, mq_flags, mq_maxmsg, mq_msgsize, mq_curmsgs);
        same_struct!(
            msghdr,
            msg_name,
            msg_namelen,
            msg_iov,
            msg_iovlen,
            msg_control,
            msg_controllen,
            msg_flags,
        );
        same_struct!(
            msqid_ds,
            msg_perm,
            msg_stime,
            msg_rtime,
            msg_ctime,
            __msg_cbytes,
            msg_qnum,
            msg_qbytes,
            msg_lspid,
            msg_lrpid,
        );
        same_struct!(pollfd, fd, events, revents);
        same_struct!(rlimit, rlim_cur, rlim_max);
        same_struct!(rlimit64, rlim_cur, rlim_max);
        same_struct!(
            rusage,
            ru_utime,
            ru_stime,
            ru_maxrss,
            ru_ixrss,
            ru_idrss,
            ru_isrss,
            ru_minflt,
            ru_majflt,
            ru_nswap,
            ru_inblock,
            ru_oublock,
            ru_msgsnd,
            ru_msgrcv,
            ru_nsignals,
            ru_nvcsw,
            ru_nivcsw,
        );
        same_struct!(sched_param, sched_priority);
        same_struct!(sembuf, sem_num, sem_op, sem_flg);
        same_struct!(
            shmid_ds, shm_perm, shm_segsz, shm_atime, shm_dtime, shm_ctime, shm_cpid, shm_lpid,
            shm_nattch,
        );
        same_struct!(sigaction, sa_sigaction, sa_mask, sa_flags, sa_restorer);
        same_struct!(
            sigevent,
            sigev_value,
            sigev_signo,
            sigev_notify,
            sigev_notify_thread_id
        );
        same_struct!(siginfo_t, si_signo, si_errno, si_code, _pad);
        // `sigset_t` has no public fields.
        same_struct!(sigset_t);
        same_struct!(sigval, sival_ptr);
        same_struct!(sockaddr, sa_family, sa_data);
        same_struct!(stack_t, ss_sp, ss_flags, ss_size);
        same_struct!(
            stat,
            st_dev,
            st_ino,
            st_nlink,
            st_mode,
            st_uid,
            st_gid,
            st_rdev,
            st_size,
            st_blksize,
            st_blocks,
            st_atime,
            st_atime_nsec,
            st_mtime,
            st_mtime_nsec,
            st_ctime,
            st_ctime_nsec,
        );
        same_struct!(
            statfs, f_type, f_bsize, f_blocks, f_bfree, f_bavail, f_files, f_ffree, f_fsid,
            f_namelen, f_frsize,
        );
        same_struct!(
            statx,
            stx_mask,
            stx_blksize,
            stx_attributes,
            stx_nlink,
            stx_uid,
            stx_gid,
            stx_mode,
            stx_ino,
            stx_size,
            stx_blocks,
            stx_attributes_mask,
            stx_atime,
            stx_btime,
            stx_ctime,
            stx_mtime,
            stx_rdev_major,
            stx_rdev_minor,
            stx_dev_major,
            stx_dev_minor,
            stx_mnt_id,
            stx_dio_mem_align,
            stx_dio_offset_align,
            stx_subvol,
            stx_atomic_write_unit_min,
            stx_atomic_write_unit_max,
            stx_atomic_write_segments_max,
            stx_dio_read_offset_align,
            stx_atomic_write_unit_max_opt,
        );
        same_struct!(statx_timestamp, tv_sec, tv_nsec);
        same_struct!(
            sysinfo, uptime, loads, totalram, freeram, sharedram, bufferram, totalswap, freeswap,
            procs, pad, totalhigh, freehigh, mem_unit, _f,
        );
        same_struct!(timespec, tv_sec, tv_nsec);
        same_struct!(timeval, tv_sec, tv_usec);
        same_struct!(
            timex, modes, offset, freq, maxerror, esterror, status, constant, precision, tolerance,
            time, tick, ppsfreq, jitter, shift, stabil, jitcnt, calcnt, errcnt, stbcnt, tai,
            __unused1, __unused2, __unused3, __unused4, __unused5, __unused6, __unused7, __unused8,
            __unused9, __unused10, __unused11,
        );
        // `timezone` has no public fields.
        same_struct!(timezone);
        same_struct!(tms, tms_utime, tms_stime, tms_cutime, tms_cstime);
        same_struct!(
            user_regs_struct,
            r15,
            r14,
            r13,
            r12,
            rbp,
            rbx,
            r11,
            r10,
            r9,
            r8,
            rax,
            rcx,
            rdx,
            rsi,
            rdi,
            orig_rax,
            rip,
            cs,
            eflags,
            rsp,
            ss,
            fs_base,
            gs_base,
            ds,
            es,
            fs,
            gs,
        );
        same_struct!(utimbuf, actime, modtime);
        same_struct!(
            utsname, sysname, nodename, release, version, machine, domainname
        );
    }
}
