// @generated by reverie-syscalls/shim-gen/regen.sh from nix 0.30.1
// (x86_64-unknown-linux-gnu). Do not edit by hand: regenerate, then run the
// reverie-syscalls host tests, which check every item here against `nix`.

//! The `nix` types that reverie-syscalls names, for builds without `std`.
//!
//! nix requires `std`. With `std` off, this module stands in for nix under the
//! same paths (`crate::nix::fcntl::OFlag` and so on). Each flags type is
//! declared with the `bitflags` crate nix uses, the derives nix's
//! `libc_bitflags!` uses, and nix's own flag table in order, so values, names
//! and `Debug` output are nix's. The tests at the end of this file check that
//! against nix on the host.

#![allow(missing_docs)]

pub mod unistd {
    use core::fmt;

    use crate::libc::pid_t;

    /// Look-alike of `nix::unistd::Pid`, without the calls into the host
    /// (`this`, `parent`).
    #[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
    pub struct Pid(pid_t);

    impl Pid {
        /// Creates `Pid` from raw `pid_t`.
        pub const fn from_raw(pid: pid_t) -> Self {
            Pid(pid)
        }

        /// Returns PID's raw `pid_t`.
        pub const fn as_raw(self) -> pid_t {
            self.0
        }
    }

    impl From<Pid> for pid_t {
        fn from(pid: Pid) -> Self {
            pid.0
        }
    }

    impl fmt::Display for Pid {
        fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
            fmt::Display::fmt(&self.0, f)
        }
    }
}

pub mod fcntl {
    bitflags::bitflags! {
        /// Look-alike of `nix::fcntl::OFlag`.
        #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
        #[repr(transparent)]
        pub struct OFlag: i32 {
            const O_ACCMODE = 0x3;
            const O_APPEND = 0x400;
            const O_ASYNC = 0x2000;
            const O_CLOEXEC = 0x80000;
            const O_CREAT = 0x40;
            const O_DIRECT = 0x4000;
            const O_DIRECTORY = 0x10000;
            const O_DSYNC = 0x1000;
            const O_EXCL = 0x80;
            const O_FSYNC = 0x101000;
            const O_LARGEFILE = 0x0;
            const O_NOATIME = 0x40000;
            const O_NOCTTY = 0x100;
            const O_NDELAY = 0x800;
            const O_NOFOLLOW = 0x20000;
            const O_NONBLOCK = 0x800;
            const O_PATH = 0x200000;
            const O_RDONLY = 0x0;
            const O_RDWR = 0x2;
            const O_RSYNC = 0x101000;
            const O_SYNC = 0x101000;
            const O_TMPFILE = 0x410000;
            const O_TRUNC = 0x200;
            const O_WRONLY = 0x1;
        }
    }
    bitflags::bitflags! {
        /// Look-alike of `nix::fcntl::AtFlags`.
        #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
        #[repr(transparent)]
        pub struct AtFlags: i32 {
            const AT_REMOVEDIR = 0x200;
            const AT_SYMLINK_FOLLOW = 0x400;
            const AT_SYMLINK_NOFOLLOW = 0x100;
            const AT_NO_AUTOMOUNT = 0x800;
            const AT_EMPTY_PATH = 0x1000;
            const AT_EACCESS = 0x200;
        }
    }
}
pub mod sched {
    bitflags::bitflags! {
        /// Look-alike of `nix::sched::CloneFlags`.
        #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
        #[repr(transparent)]
        pub struct CloneFlags: i32 {
            const CLONE_VM = 0x100;
            const CLONE_FS = 0x200;
            const CLONE_FILES = 0x400;
            const CLONE_SIGHAND = 0x800;
            const CLONE_PTRACE = 0x2000;
            const CLONE_VFORK = 0x4000;
            const CLONE_PARENT = 0x8000;
            const CLONE_THREAD = 0x10000;
            const CLONE_NEWNS = 0x20000;
            const CLONE_SYSVSEM = 0x40000;
            const CLONE_DETACHED = 0x400000;
            const CLONE_UNTRACED = 0x800000;
            const CLONE_NEWCGROUP = 0x2000000;
            const CLONE_NEWUTS = 0x4000000;
            const CLONE_NEWIPC = 0x8000000;
            const CLONE_NEWUSER = 0x10000000;
            const CLONE_NEWPID = 0x20000000;
            const CLONE_NEWNET = 0x40000000;
            const CLONE_IO = -2147483648;
        }
    }
}
pub mod sys {
    pub mod epoll {
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::epoll::EpollCreateFlags`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct EpollCreateFlags: i32 {
                const EPOLL_CLOEXEC = 0x80000;
            }
        }
    }
    pub mod eventfd {
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::eventfd::EfdFlags`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct EfdFlags: i32 {
                const EFD_CLOEXEC = 0x80000;
                const EFD_NONBLOCK = 0x800;
                const EFD_SEMAPHORE = 0x1;
            }
        }
    }
    pub mod inotify {
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::inotify::InitFlags`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct InitFlags: i32 {
                const IN_CLOEXEC = 0x80000;
                const IN_NONBLOCK = 0x800;
            }
        }
    }
    pub mod mman {
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::mman::MapFlags`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct MapFlags: i32 {
                const MAP_FILE = 0x0;
                const MAP_SHARED = 0x1;
                const MAP_SHARED_VALIDATE = 0x3;
                const MAP_PRIVATE = 0x2;
                const MAP_FIXED = 0x10;
                const MAP_FIXED_NOREPLACE = 0x100000;
                const MAP_ANON = 0x20;
                const MAP_ANONYMOUS = 0x20;
                const MAP_32BIT = 0x40;
                const MAP_GROWSDOWN = 0x100;
                const MAP_DENYWRITE = 0x800;
                const MAP_EXECUTABLE = 0x1000;
                const MAP_LOCKED = 0x2000;
                const MAP_NORESERVE = 0x4000;
                const MAP_POPULATE = 0x8000;
                const MAP_NONBLOCK = 0x10000;
                const MAP_HUGETLB = 0x40000;
                const MAP_HUGE_64KB = 0x40000000;
                const MAP_HUGE_512KB = 0x4c000000;
                const MAP_HUGE_1MB = 0x50000000;
                const MAP_HUGE_2MB = 0x54000000;
                const MAP_HUGE_8MB = 0x5c000000;
                const MAP_HUGE_16MB = 0x60000000;
                const MAP_HUGE_32MB = 0x64000000;
                const MAP_HUGE_256MB = 0x70000000;
                const MAP_HUGE_512MB = 0x74000000;
                const MAP_HUGE_1GB = 0x78000000;
                const MAP_HUGE_2GB = 0x7c000000;
                const MAP_HUGE_16GB = -2013265920;
                const MAP_STACK = 0x20000;
                const MAP_SYNC = 0x80000;
            }
        }
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::mman::ProtFlags`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct ProtFlags: i32 {
                const PROT_NONE = 0x0;
                const PROT_READ = 0x1;
                const PROT_WRITE = 0x2;
                const PROT_EXEC = 0x4;
                const PROT_GROWSDOWN = 0x1000000;
                const PROT_GROWSUP = 0x2000000;
            }
        }
    }
    pub mod signalfd {
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::signalfd::SfdFlags`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct SfdFlags: i32 {
                const SFD_NONBLOCK = 0x800;
                const SFD_CLOEXEC = 0x80000;
            }
        }
    }
    pub mod socket {
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::socket::SockFlag`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct SockFlag: i32 {
                const SOCK_NONBLOCK = 0x800;
                const SOCK_CLOEXEC = 0x80000;
            }
        }
    }
    pub mod stat {
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::stat::Mode`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct Mode: u32 {
                const S_IRWXU = 0x1c0;
                const S_IRUSR = 0x100;
                const S_IWUSR = 0x80;
                const S_IXUSR = 0x40;
                const S_IRWXG = 0x38;
                const S_IRGRP = 0x20;
                const S_IWGRP = 0x10;
                const S_IXGRP = 0x8;
                const S_IRWXO = 0x7;
                const S_IROTH = 0x4;
                const S_IWOTH = 0x2;
                const S_IXOTH = 0x1;
                const S_ISUID = 0x800;
                const S_ISGID = 0x400;
                const S_ISVTX = 0x200;
            }
        }
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::stat::SFlag`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct SFlag: u32 {
                const S_IFIFO = 0x1000;
                const S_IFCHR = 0x2000;
                const S_IFDIR = 0x4000;
                const S_IFBLK = 0x6000;
                const S_IFREG = 0x8000;
                const S_IFLNK = 0xa000;
                const S_IFSOCK = 0xc000;
                const S_IFMT = 0xf000;
            }
        }
    }
    pub mod timerfd {
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::timerfd::TimerFlags`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct TimerFlags: i32 {
                const TFD_NONBLOCK = 0x800;
                const TFD_CLOEXEC = 0x80000;
            }
        }
    }
    pub mod wait {
        bitflags::bitflags! {
            /// Look-alike of `nix::sys::wait::WaitPidFlag`.
            #[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            #[repr(transparent)]
            pub struct WaitPidFlag: i32 {
                const WNOHANG = 0x1;
                const WUNTRACED = 0x2;
                const WEXITED = 0x4;
                const WCONTINUED = 0x8;
                const WSTOPPED = 0x2;
                const WNOWAIT = 0x1000000;
                const __WNOTHREAD = 0x20000000;
                const __WALL = 0x40000000;
                const __WCLONE = -2147483648;
            }
        }
    }
}

#[cfg(all(test, feature = "std"))]
mod tests {
    use core::fmt::Debug;

    use bitflags::Bits;
    use bitflags::Flags;

    /// `A` must have `B`'s flag table (names and values, in order) and the
    /// same `Debug` output for every flag, for no flags, for all bits, and
    /// for all known flags.
    fn same_flags<A, B, X>()
    where
        A: Flags<Bits = X> + Debug,
        B: Flags<Bits = X> + Debug,
        X: Bits + Debug + PartialEq,
    {
        let ours: Vec<(&str, X)> = A::FLAGS
            .iter()
            .map(|f| (f.name(), f.value().bits()))
            .collect();
        let theirs: Vec<(&str, X)> = B::FLAGS
            .iter()
            .map(|f| (f.name(), f.value().bits()))
            .collect();
        assert_eq!(ours, theirs);
        let mut samples: Vec<X> = ours.iter().map(|&(_, bits)| bits).collect();
        samples.extend([X::EMPTY, X::ALL, A::all().bits()]);
        for bits in samples {
            assert_eq!(
                format!("{:?}", A::from_bits_retain(bits)),
                format!("{:?}", B::from_bits_retain(bits)),
            );
        }
    }

    #[test]
    fn flags_match_nix() {
        same_flags::<super::fcntl::OFlag, nix::fcntl::OFlag, _>();
        same_flags::<super::fcntl::AtFlags, nix::fcntl::AtFlags, _>();
        same_flags::<super::sched::CloneFlags, nix::sched::CloneFlags, _>();
        same_flags::<super::sys::epoll::EpollCreateFlags, nix::sys::epoll::EpollCreateFlags, _>();
        same_flags::<super::sys::eventfd::EfdFlags, nix::sys::eventfd::EfdFlags, _>();
        same_flags::<super::sys::inotify::InitFlags, nix::sys::inotify::InitFlags, _>();
        same_flags::<super::sys::mman::MapFlags, nix::sys::mman::MapFlags, _>();
        same_flags::<super::sys::mman::ProtFlags, nix::sys::mman::ProtFlags, _>();
        same_flags::<super::sys::signalfd::SfdFlags, nix::sys::signalfd::SfdFlags, _>();
        same_flags::<super::sys::socket::SockFlag, nix::sys::socket::SockFlag, _>();
        same_flags::<super::sys::stat::Mode, nix::sys::stat::Mode, _>();
        same_flags::<super::sys::stat::SFlag, nix::sys::stat::SFlag, _>();
        same_flags::<super::sys::timerfd::TimerFlags, nix::sys::timerfd::TimerFlags, _>();
        same_flags::<super::sys::wait::WaitPidFlag, nix::sys::wait::WaitPidFlag, _>();
    }

    #[test]
    fn pid_matches_nix() {
        for raw in [i32::MIN, -1, 0, 1, 42, i32::MAX] {
            let ours = super::unistd::Pid::from_raw(raw);
            let theirs = nix::unistd::Pid::from_raw(raw);
            assert_eq!(ours.as_raw(), theirs.as_raw());
            assert_eq!(i32::from(ours), i32::from(theirs));
            assert_eq!(format!("{ours}"), format!("{theirs}"));
            assert_eq!(format!("{ours:?}"), format!("{theirs:?}"));
        }
    }
}
