#!/usr/bin/env bash
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Prints every global symbol of the 64-bit vDSO linker scripts of a Linux
# release, one per line in script order, as the checked-in lists in this
# directory hold them. Symbols under `#ifdef` are included: a kernel built with
# the option exports them.
#
# Usage: linux-vdso-symbols.sh LINUX_GIT_DIR REV ARCH
#   ARCH is x86_64 or aarch64.
#
# Example, auditing a new release:
#   reverie/tests/vdso/linux-vdso-symbols.sh ~/linux v7.3 x86_64 \
#     | diff reverie/tests/vdso/linux-v7.2-x86_64.txt -
# A new name needs a VdsoSymbol variant (reverie/src/vdso.rs) and a list
# regenerated for that release; the vdso_symbols test reads the lists.

set -euo pipefail

if [ "$#" -ne 3 ]; then
  echo "usage: $0 LINUX_GIT_DIR REV ARCH" >&2
  exit 2
fi
linux=$1
rev=$2
arch=$3

case "$arch" in
  x86_64)
    # The 64-bit script, then the x32 one; Linux v7.0 moved them into vdso64/.
    primaries=(
      arch/x86/entry/vdso/vdso64/vdso64.lds.S
      arch/x86/entry/vdso/vdso.lds.S
    )
    candidates=(
      arch/x86/entry/vdso/vdso64/vdso64.lds.S
      arch/x86/entry/vdso/vdso64/vdsox32.lds.S
      arch/x86/entry/vdso/vdso.lds.S
      arch/x86/entry/vdso/vdsox32.lds.S
    )
    ;;
  aarch64)
    primaries=(arch/arm64/kernel/vdso/vdso.lds.S)
    candidates=(arch/arm64/kernel/vdso/vdso.lds.S)
    ;;
  *)
    echo "unknown ARCH $arch" >&2
    exit 2
    ;;
esac

commit=$(git -C "$linux" rev-parse --short=12 "$rev^{commit}")
scripts=()
for path in "${candidates[@]}"; do
  if git -C "$linux" cat-file -e "$commit:$path" 2>/dev/null; then
    scripts+=("$path")
  fi
done
# A list without the 64-bit script would silently omit its names, so a
# release that moves it again must fail here rather than print a short list.
primary=
for path in "${primaries[@]}"; do
  if git -C "$linux" cat-file -e "$commit:$path" 2>/dev/null; then
    primary=$path
    break
  fi
done
if [ -z "$primary" ]; then
  echo "no 64-bit vDSO linker script for $arch at $rev (looked for ${primaries[*]})" >&2
  exit 1
fi

echo "# Global symbols of the Linux $rev ($commit) $arch vDSO, from"
for path in "${scripts[@]}"; do
  echo "# $path"
done
echo "# Generated by reverie/tests/vdso/linux-vdso-symbols.sh."
for path in "${scripts[@]}"; do
  # Every name in each `global:` section of the VERSION block, which ends at
  # `local:` or at the closing brace of its version node, after dropping
  # comments and preprocessor lines. Anything else in a section, such as a
  # quoted name, a glob or a name with no `;`, is an error rather than a
  # silently shorter list.
  git -C "$linux" show "$commit:$path" | awk -v script="$path" '
    function fail(why) {
      printf "%s: %s\n", script, why > "/dev/stderr"
      failed = 1
      exit 1
    }
    /^[[:space:]]*#/ { next }
    { text = text $0 "\n" }
    END {
      if (failed) exit 1
      while ((open = index(text, "/*")) > 0) {
        rest = substr(text, open + 2)
        close_at = index(rest, "*/")
        if (close_at == 0) fail("unterminated comment")
        text = substr(text, 1, open - 1) " " substr(rest, close_at + 2)
      }
      if (!match(text, /VERSION[[:space:]]*\{/)) fail("no VERSION block")
      text = substr(text, RSTART + RLENGTH)
      count = 0
      while ((at = index(text, "global:")) > 0) {
        text = substr(text, at + 7)
        local_at = index(text, "local:")
        brace_at = index(text, "}")
        if (brace_at == 0) fail("global section never closes")
        stop = (local_at > 0 && local_at < brace_at) ? local_at : brace_at
        section = substr(text, 1, stop - 1)
        text = substr(text, stop)
        n = split(section, parts, ";")
        for (i = 1; i <= n; i++) {
          name = parts[i]
          gsub(/[[:space:]]/, "", name)
          if (name == "") continue
          if (i == n) fail("name without a terminating semicolon: " name)
          if (name !~ /^[A-Za-z_][A-Za-z0-9_]*$/) fail("not a plain symbol name: " name)
          print name
          count++
        }
      }
      if (count == 0) fail("no global names")
    }
  '
done | awk '!seen[$0]++'
